from __future__ import annotations
from copy import deepcopy
from datetime import date
from typing import Any
K=("traffic_diagnostic","traffic_record_request","traffic_notification_claim","traffic_hearing_request","traffic_revocation_request","traffic_registry_correction","traffic_evidence_matrix","traffic_filing_guide")
T={"traffic_diagnostic":"Diagnóstico jurídico del expediente de fotodetección y tránsito","traffic_record_request":"Petición integral de expediente contravencional y estado procesal","traffic_notification_claim":"Reclamación por notificación no acreditada o irregular","traffic_hearing_request":"Comparecencia, audiencia y solicitud de pruebas","traffic_revocation_request":"Ficha condicionada para eventual revocación directa","traffic_registry_correction":"Solicitud condicionada de corrección y sincronización de registros","traffic_evidence_matrix":"Matriz probatoria, cronológica y de términos del expediente","traffic_filing_guide":"Guía de radicación, alertas procesales y cierre del caso"}
ST={k:v for k,v in zip(K,("Detección · validación · envío · notificación · defensa · sanción · ejecutoria · cobro","Expediente íntegro · trazabilidad postal · responsabilidad · sanción · cobro","Debido proceso · vinculación · defensa material · restablecimiento condicionado","Acceso a pruebas · contradicción · imputación personal · decisión motivada","Causales · procedencia · límites · términos judiciales · efectos","Acto fuente · SIMIT/RUNT · consistencia · trazabilidad de actualización","Hitos · documentos · vacíos · caducidad · prescripción · cobro","Radicado · acto adverso · recurso · cobro · revisión profesional"))}
SRC=["Constitución Política, art. 29.","Ley 769 de 2002, arts. 129, 136, 159 y 161, con modificaciones vigentes.","Ley 1843 de 2017, arts. 7, 8, 9 y 11.","Ley 2161 de 2021, art. 10, corregido por Decreto 998 de 2022.","Corte Constitucional C-038/2020 y C-321/2022.","Resolución Única de Tránsito 20223040045295 de 2022 y modificaciones.","Ley 1437 de 2011, arts. 67–69 y 93–96.","Ley 1755 de 2015, arts. 14 y 21."]
def v(x:Any,f="Por verificar"):return f if x in(None,"",[],{}) else str(x)
def pd(x):
 try:return date.fromisoformat(str(x)[:10]) if x else None
 except:return None
def de(x):
 d=pd(x); m=("enero","febrero","marzo","abril","mayo","junio","julio","agosto","septiembre","octubre","noviembre","diciembre")
 return f"{d.day} de {m[d.month-1]} de {d.year}" if d else v(x,"Fecha por verificar")
def who(a):return v(a.get("requester_name") or a.get("owner_name"),"Persona por identificar")
def sig(a,l):return {"heading":"FIRMA","_type":"signature","heading_align":"center","parties":[{"label":l,"name":who(a),"id":v(a.get("requester_id") or a.get("owner_id"),"")}]}
def start(h,p):return {"heading":h,"paragraphs":p,"_suppress_default_control":True}
def addr(a):
 o=str(a.get("official_address") or "");u=str(a.get("used_address") or "")
 return ("Inconsistencia aparente de dirección",f"Dato oficial informado: «{o}». Dato usado: «{u}». Debe obtenerse certificación histórica RUNT de la fecha de consulta, trazabilidad de la fuente, guía postal y soporte de notificación subsidiaria; la diferencia no produce por sí sola nulidad.") if o and u and o.casefold()!=u.casefold() else ("Notificación por reconstruir","Envío, entrega, subsidiaria y conocimiento real deben probarse separadamente.")
def notif(a):
 l,d=addr(a);return ["Detección, validación y envío son hitos distintos: controlar validación frente a diez (10) días hábiles y envío frente a tres (3) días hábiles siguientes a la validación.","La comparecencia en fotodetección se prevé dentro de once (11) días hábiles siguientes al recibo; despacho o guía no equivalen a recibo.","Si no se surte la notificación en la última dirección registrada, debe acreditarse el mecanismo subsidiario realmente utilizado.","Conocimiento tardío por consulta o cobro no equivale automáticamente a notificación válida.","Si se prueba falta o indebida notificación, el art. 136 dispone que los términos de reducción corran desde la notificación válida; otros efectos exigen reconstruir el expediente y la afectación material de defensa.",f"Clasificación preliminar: {l}. {d}"]
def owner(a):return ["C-038/2020 eliminó la solidaridad automática propietario-conductor: la titularidad sola no traslada una conducta ajena.","C-321/2022 precisó que el art. 10 de Ley 2161 contiene deberes propios del propietario; para lugares/horarios no permitidos, velocidad y luz roja, sancionarlo exige prueba de incumplimiento culposo dentro del procedimiento, no responsabilidad objetiva.","La autoridad debe individualizar si imputa conducción o deber propio del propietario, norma, hechos, prueba y culpabilidad, con oportunidad real de contradicción."]
def terms(a):return [f"Caducidad: art. 161, un (1) año desde el hecho para decidir la imposición de sanción. Hecho: {de(a.get('detection_date'))}; decisión: {de(a.get('sanction_date'))}. Sin acto y fecha ciertos no se declara.",f"Prescripción: art. 159, tres (3) años desde el hecho; se interrumpe con la notificación del mandamiento de pago. Mandamiento: {de(a.get('payment_order_date'))}. Sin expediente coactivo no se concluye.","Caducidad, prescripción, ejecutoria y cobro son controles distintos."]
def tl(a):return [["Hito","Fecha","Soporte"],["Detección",de(a.get("detection_date")),"Original/metadatos"],["Validación",de(a.get("validation_date")),"Registro de validación"],["Consulta RUNT",de(a.get("registry_query_date")),"Certificación histórica"],["Envío",de(a.get("mailing_date")),"Guía/imposición"],["Entrega/devolución",de(a.get("delivery_or_return_date")),v(a.get("postal_result"))],["Subsidiaria",de(a.get("notice_date")),v(a.get("secondary_notification"))],["Conocimiento real",de(a.get("actual_knowledge_date")),"No equivale automáticamente a notificación"],["Sanción",de(a.get("sanction_date")),v(a.get("sanction_resolution"))],["Ejecutoria",de(a.get("enforceability_date")),"Constancia"],["Mandamiento",de(a.get("payment_order_date")),v(a.get("collection_exists"))]]
def diagnostic(a,r):
 l,d=addr(a);return [start("OBJETO Y ALCANCE",["Reconstruye el expediente individual; no declara automáticamente nulidad, responsabilidad, prescripción, no pago, devolución ni invalidez del SAST.","Cada conclusión debe vincularse con acto, fecha y soporte; un vacío probatorio no se rellena por inferencia."]),{"heading":"I. IDENTIFICACIÓN","table":[["Elemento","Dato"],["Persona",who(a)],["Placa",v(a.get("vehicle_plate"))],["Comparendo",v(a.get("citation_number"))],["Autoridad",v(a.get("traffic_authority"))],["Hecho",de(a.get("detection_date"))],["Pago",v(a.get("paid"))]]},{"heading":"II. CRONOLOGÍA","table":tl(a)},{"heading":"III. NOTIFICACIÓN","numbered":notif(a)},{"heading":"IV. RESPONSABILIDAD","numbered":owner(a)},{"heading":"V. CADUCIDAD, PRESCRIPCIÓN Y COBRO","numbered":terms(a)},{"heading":"VI. CONCLUSIÓN","paragraphs":[f"{l}. {d}","Primero deben obtenerse actos y soportes. Luego se define audiencia, reclamación, recurso, revocación, corrección registral, defensa de cobro o vía judicial."]},{"heading":"VII. FUENTES","numbered":SRC}]
def record(a,r):return [start("ASUNTO Y ALCANCE",[f"Petición del expediente del comparendo {v(a.get('citation_number'))}, placa {v(a.get('vehicle_plate'))}. No acepta infracción, conducción, ejecutoria ni deuda."]),{"heading":"I. DETECCIÓN Y VALIDACIÓN","numbered":["Original y metadatos de evidencia.","Registro de validación, fecha/hora y funcionario competente.","Identificación del SAST, punto y soportes del período."]},{"heading":"II. DATOS Y NOTIFICACIÓN","numbered":["Certificación histórica RUNT a la fecha consultada.",f"Explicar fuente del dato usado: oficial informado «{v(a.get('official_address'))}»; utilizado «{v(a.get('used_address'))}».","Guía, imposición, intentos, entrega/devolución y certificación postal.","Notificación electrónica, aviso o subsidiaria con contenido y fechas.","Precisar actuación que produjo vinculación e inicio de defensa."]},{"heading":"III. SANCIÓN Y COBRO","numbered":["Audiencias, actas, grabaciones y pruebas.","Resolución sancionatoria íntegra, notificación, recursos y ejecutoria.","Calidad de imputación y juicio de responsabilidad.","Si existe cobro: título, mandamiento, notificación, excepciones, acuerdos y cautelares.","Pagos y novedades SIMIT/RUNT."]},{"heading":"IV. TÉRMINOS Y RESERVA","numbered":["Información/documentos: diez (10) días; demás peticiones: en principio quince (15), salvo regla especial.","Incompetencia: traslado dentro de cinco (5) días.","Reserva: norma específica y versión pública cuando proceda.","Documento inexistente/no custodiado: declararlo expresamente."]},sig(a,"PERSONA PETICIONARIA")]
def claim(a,r):
 l,d=addr(a);return [start("REGLA DE ACTIVACIÓN",["Solo procede con evidencia que permita cuestionar la notificación; no convierte ‘no recibí’ en nulidad automática.",f"{l}. {d}"]),{"heading":"I. HECHOS","table":[["Dato","Información"],["Consulta",de(a.get("registry_query_date"))],["Dirección oficial",v(a.get("official_address"))],["Dirección usada",v(a.get("used_address"))],["Envío",de(a.get("mailing_date"))],["Resultado",v(a.get("postal_result"))],["Subsidiaria",v(a.get("secondary_notification"))],["Conocimiento real",de(a.get("actual_knowledge_date"))]]},{"heading":"II. REGLAS","numbered":notif(a)},{"heading":"III. DEFENSA MATERIAL","numbered":["Verificar oportunidad de conocer comparendo y soportes.","Verificar audiencia, pruebas y contradicción.","Verificar resolución y su notificación separada.","No presumir saneamiento por conocimiento tardío."]},{"heading":"IV. SOLICITUDES","numbered":["Decidir validez de notificación con dato histórico y trazabilidad.","Si se acredita defecto, surtir notificación procedente y efectos del art. 136.","Restablecer defensa cuando jurídicamente corresponda.","No tratar esta reclamación como suspensión automática del cobro o términos judiciales."]},sig(a,"PERSONA RECLAMANTE")]
def hearing(a,r):return [start("COMPARECENCIA Y RESERVA",["Ejercer defensa no confiesa conducción, acepta infracción ni renuncia a cuestionar notificación/evidencia."]),{"heading":"I. CUESTIONES PREVIAS","numbered":["Incorporar comparendo y prueba de vinculación.","Individualizar código, hecho, lugar y evidencia.","Precisar conducción o deber propio del propietario.","Resolver acceso al expediente."]},{"heading":"II. PRUEBAS","numbered":["Original/metadatos.","Validación y competencia.","SAST/punto y soportes.","Dato histórico y trazabilidad de notificación.","Prueba de responsabilidad personal.","Prueba de descargo."]},{"heading":"III. RESPONSABILIDAD","numbered":owner(a)},{"heading":"IV. DECISIÓN","numbered":["Contradicción efectiva.","Motivar negativa probatoria.","Explicar hechos, pruebas y norma.","Diferenciar comparendo, sanción y ejecutoria.","Notificar e informar recursos/términos."]},sig(a,"PERSONA COMPARECIENTE")]
def revocation(a,r):
 ok=bool(a.get("sanction_resolution")) and pd(a.get("sanction_date"));st="Activación documental posible" if ok else "NO RADICABLE TODAVÍA — falta individualizar y obtener el acto sancionatorio"
 return [start("ESTADO DE ACTIVACIÓN",[st,"Requiere acto, notificación, recursos, ejecutoria, demanda, pago y cobro; no sustituye recursos ni revive términos."]),{"heading":"I. ACTO","table":[["Resolución",v(a.get("sanction_resolution"))],["Fecha",de(a.get("sanction_date"))],["Notificación",v(a.get("sanction_notification"))],["Ejecutoria",de(a.get("enforceability_date"))],["Cobro",v(a.get("collection_exists"))],["Pago",v(a.get("paid"))]]},{"heading":"II. PROCEDENCIA","numbered":["Causal concreta del art. 93 CPACA y prueba.","Revisar art. 94, recursos y medio de control.","Verificar proceso judicial y art. 95.","Revisar regla especial/supletiva del art. 161 de tránsito."]},{"heading":"III. LÍMITES","numbered":["No produce silencio positivo.","No revive términos judiciales.","No suspende automáticamente ejecución/cobro/cautelares.","Decisión favorable debe ejecutarse según su alcance."]},{"heading":"IV. REVISIÓN PROFESIONAL","paragraphs":["Con término judicial, cobro, embargo, pago o acto firme, revisar expediente exacto antes de radicar."]},sig(a,"PERSONA SOLICITANTE")]
def registry(a,r):
 s=v(a.get("registry_source_act"),"Acto fuente por verificar");return [start("REGLA DE ACTIVACIÓN",["Corrección registral exige acto, pago, archivo, revocación, decisión judicial u otro soporte idóneo; una inconsistencia visual no basta.",f"Soporte: {s}."]),{"heading":"I. SOLICITUDES","numbered":["Ejecutar el acto fuente dentro de su alcance.","Actualizar base interna y transmitir novedad.","Informar fecha, identificador y resultado.","Verificar recepción y corregir residuales.","Explicar anotaciones que deban conservarse y diferenciarlas de deuda exigible."]},{"heading":"II. CIERRE","paragraphs":["Cerrar solo con evidencia del estado final de cada sistema y correspondencia con el acto fuente."]},sig(a,"PERSONA SOLICITANTE")]
def evidence(a,r):return [start("OBJETO",["Organiza soportes para decidir cada hito sin calcular consecuencias a partir de fechas incompletas."]),{"heading":"I. CRONOLOGÍA","table":tl(a)},{"heading":"II. NOTIFICACIÓN","numbered":["Dato histórico RUNT.","Canal usado y fuente.","Guía/imposición/intentos/resultado.","Subsidiaria completa.","Notificación separada de la resolución."]},{"heading":"III. RESPONSABILIDAD","numbered":owner(a)},{"heading":"IV. TÉRMINOS","numbered":terms(a)},{"heading":"V. RESULTADOS ADMISIBLES","paragraphs":["Acreditado, inconsistencia documentada, no acreditado, no calculable o escalamiento profesional; no anulación/prescripción/no pago/devolución automáticos."]}]
def guide(a,r):return [start("RADICACIÓN Y TRAZABILIDAD",["Conservar escrito/anexos, fecha/hora/canal/radicado y recepción; separar expediente contravencional, SAST y cobro."]),{"heading":"I. ALERTA DE ACTO ADVERSO","paragraphs":["Resolución, recurso, mandamiento, cautelar o providencia exige revisión inmediata de número, fecha, notificación, recursos y límite."]},{"heading":"II. SEMÁFORO","table":[["Estado","Acción"],["Comparendo sin notificación acreditada","Obtener expediente"],["Defensa abierta","Audiencia/pruebas"],["Resolución no firme","Recursos/términos"],["Resolución firme","Medio judicial/revocación/cobro"],["Mandamiento","Notificación/prescripción/excepciones"],["Embargo","Revisión urgente"],["Pago","Ruta eventual sin prometer resultado"]]},{"heading":"III. NO COLAPSAR","numbered":["Comparendo ≠ sanción.","Validación ≠ notificación.","Envío ≠ entrega.","Conocimiento tardío ≠ notificación válida.","Propietario ≠ conductor, pero puede tener deberes propios.","Falta de notificación ≠ nulidad universal.","Caducidad ≠ prescripción.","SIMIT/RUNT ≠ acto fuente.","Revocación ≠ suspensión o reapertura judicial."]},{"heading":"IV. LENGUAJE","paragraphs":["Describir acreditación y vacíos; no concluir automáticamente ‘fotomulta ilegal’, ‘multa anulada’, ‘no tiene que pagar’, ‘prescribió’ o ‘devolución obligatoria’."]},{"heading":"V. REVISIÓN HUMANA","paragraphs":["Obligatoria antes de uso externo e inmediata ante acto adverso, recurso próximo, cobro, embargo, pago o proceso judicial."]}]
B=dict(zip(K,(diagnostic,record,claim,hearing,revocation,registry,evidence,guide)))
def finalize_traffic_specs(specs:list[dict],a:dict,r:dict)->list[dict]:
 src={str(s.get("kind")):deepcopy(s) for s in specs if str(s.get("kind")) in K};meta=deepcopy(specs[0].get("metadata",[])) if specs else [];out=[]
 for k in K:
  s=src.get(k,{"kind":k,"filename_suffix":k,"metadata":meta});s.update(title=T[k],subtitle=ST[k],sections=B[k](a,r),document_standard="M33.0",internal_controls_externalized=True,requires_human_review=True,critical_human_review=str(r.get("risk")or"").casefold()=="red",legal_approval="pending",qa_approval="pending",released=False,legal_sources=list(SRC));out.append(s)
 return out
