'use strict';

import { api, currentPath, dateText, esc, state, toast } from '../core.js';

const BASE='/api/m32/contact-governance';
const ROUTE='/mesa-juridica';
const cache={dashboard:null,loading:false};
let timer=null;

const purposeLabel={professional_operational:'Operativa profesional',service_transactional:'Servicio solicitado',commercial_marketing:'Comercial',collections:'Cobranza'};
const channelLabel={email:'Correo',sms:'SMS',whatsapp:'WhatsApp',phone:'Llamada'};
const reasonLabel={active_suppression:'Supresión activa',inactive_or_nonprofessional_subject:'Destinatario inactivo o no profesional',active_relationship_missing:'Relación activa no acreditada',preference_denied:'Preferencia negada',explicit_marketing_consent_missing:'Falta consentimiento comercial',authorized_collection_channel_missing:'Canal de cobranza no autorizado',transactional_basis_insufficient:'Base transaccional insuficiente',configured_holiday:'Cierre configurado',sunday:'Domingo',configured_closed_day:'Día cerrado',outside_saturday_window:'Fuera de horario del sábado',outside_weekday_window:'Fuera de horario',daily_frequency_limit:'Límite diario',weekly_channel_limit:'Límite semanal de canales'};

function professional(){return state.user&&['specialist','admin','qa'].includes(state.user.role);}
function post(path,payload){return api(path,{method:'POST',body:JSON.stringify(payload||{})});}
function fmt(value){return value?dateText(value):'Sin fecha';}

function decisionItem(item){
  const reasons=(item.reasons||[]);
  return `<article class="m329-decision ${item.allowed?'':'is-blocked'}"><div class="m329-decision-head"><b>${item.allowed?'Permitido':'Bloqueado'}</b><small>${esc(fmt(item.decided_at))}</small></div><h4>${esc(purposeLabel[item.purpose]||item.purpose)} · ${esc(channelLabel[item.channel]||item.channel)}</h4><div class="m329-meta"><span>${esc(item.subject_id)}</span><span>Base: ${esc(item.declared_basis||'No determinada')}</span><span>${esc(item.decision_id)}</span></div>${reasons.length?`<ul class="m329-reasons">${reasons.map(reason=>`<li>${esc(reasonLabel[reason]||reason)}</li>`).join('')}</ul>`:''}</article>`;
}

function notices(data){
  const rows=data?.notices||[];
  if(!rows.length)return '<p class="m329-empty">No existen avisos registrados.</p>';
  return `<div class="m329-notices">${rows.map(item=>`<article><div><b>${esc(item.name)}</b><small>${esc(item.notice_id)} · v${esc(item.version)} · ${item.active?'Activo':'Borrador'}</small></div><code>${esc(String(item.notice_sha256||'').slice(0,12))}</code>${item.can_activate?`<button class="btn ghost sm" data-m329-action="activate" data-notice="${esc(item.notice_id)}" data-version="${esc(item.version)}">Activar</button>`:''}</article>`).join('')}</div>`;
}

function relationshipForm(){return `<form class="m329-form" data-m329-form="relationship"><h3>Relación acreditada</h3><label>ID del titular<input class="input" name="subject_id" required></label><div class="row"><label>Tipo<select class="select" name="relationship_type"><option value="client">Cliente</option><option value="professional">Profesional</option><option value="vendor">Proveedor</option><option value="counterparty">Contraparte</option></select></label><label>Base<select class="select" name="lawful_basis"><option value="contract">Contrato</option><option value="user_request">Solicitud del titular</option><option value="legal_obligation">Obligación legal</option><option value="consent">Consentimiento</option><option value="operational_relationship">Relación operativa</option></select></label></div><label>Referencia de evidencia<input class="input" name="evidence_reference" placeholder="Radicado, acta o identificador interno" required></label><button class="btn secondary sm" type="submit">Registrar relación</button></form>`;}
function preferenceForm(){return `<form class="m329-form" data-m329-form="preference"><h3>Preferencia o autorización</h3><label>ID del titular<input class="input" name="subject_id" required></label><div class="row"><label>Finalidad<select class="select" name="purpose"><option value="commercial_marketing">Comercial</option><option value="collections">Cobranza</option><option value="service_transactional">Servicio solicitado</option><option value="professional_operational">Operativa profesional</option></select></label><label>Canal<select class="select" name="channel"><option value="email">Correo</option><option value="sms">SMS</option><option value="whatsapp">WhatsApp</option><option value="phone">Llamada</option></select></label></div><div class="row"><label>Estado<select class="select" name="state"><option value="granted">Concedida</option><option value="denied">Negada</option></select></label><label>Base<select class="select" name="basis"><option value="consent">Consentimiento</option><option value="contract">Contrato</option><option value="user_request">Solicitud del titular</option><option value="legal_obligation">Obligación legal</option><option value="operational_relationship">Relación operativa</option></select></label></div><label>Referencia de evidencia<input class="input" name="evidence_reference" placeholder="No se almacena el texto; se conserva su hash"></label><label>Motivo<input class="input" name="reason"></label><button class="btn secondary sm" type="submit">Registrar preferencia</button></form>`;}
function suppressionForm(){return `<form class="m329-form" data-m329-form="suppression"><h3>Supresión</h3><label>ID del titular<input class="input" name="subject_id" required></label><div class="row"><label>Alcance<select class="select" name="scope"><option value="global">Global</option><option value="channel">Canal</option><option value="purpose">Finalidad</option><option value="purpose_channel">Finalidad y canal</option></select></label><label>Canal<select class="select" name="channel"><option value="">No aplica</option><option value="email">Correo</option><option value="sms">SMS</option><option value="whatsapp">WhatsApp</option><option value="phone">Llamada</option></select></label></div><label>Finalidad<select class="select" name="purpose"><option value="">No aplica</option><option value="commercial_marketing">Comercial</option><option value="collections">Cobranza</option><option value="service_transactional">Servicio solicitado</option><option value="professional_operational">Operativa profesional</option></select></label><label>Motivo<input class="input" name="reason" required></label><button class="btn secondary sm" type="submit">Aplicar supresión</button></form>`;}
function policyForm(data){const p=data?.policy||{};return `<form class="m329-form" data-m329-form="policy"><h3>Ventana operativa</h3><div class="row"><label>Lunes a viernes desde<input class="input" type="time" name="weekday_open" value="${esc(p.weekday_open||'07:00')}"></label><label>Hasta<input class="input" type="time" name="weekday_close" value="${esc(p.weekday_close||'19:00')}"></label></div><div class="row"><label>Sábado desde<input class="input" type="time" name="saturday_open" value="${esc(p.saturday_open||'08:00')}"></label><label>Hasta<input class="input" type="time" name="saturday_close" value="${esc(p.saturday_close||'15:00')}"></label></div><label>Cierres explícitos<input class="input" name="holidays" value="${esc((p.holidays||[]).join(', '))}" placeholder="2026-12-25"></label><div class="row"><label>Máximo por día<input class="input" type="number" min="1" max="20" name="max_contacts_per_day" value="${esc(p.max_contacts_per_day||1)}"></label><label>Canales en 7 días<input class="input" type="number" min="1" max="4" name="max_channels_per_7_days" value="${esc(p.max_channels_per_7_days||1)}"></label></div><button class="btn secondary sm" type="submit">Guardar política</button></form>`;}
function noticeForm(){return `<form class="m329-form" data-m329-form="notice"><h3>Nueva versión del aviso</h3><label>Nombre<input class="input" name="name" value="Aviso de canales y finalidades" required></label><label>Texto<textarea class="textarea" rows="6" name="text" required>LegalAIZ.it informa las finalidades de contacto, los canales elegidos, los derechos del titular y los mecanismos para modificar preferencias, revocar autorizaciones o solicitar supresión.</textarea></label><button class="btn secondary sm" type="submit">Crear versión</button></form>`;}

function dashboard(data){const m=data.metrics||{}, decisions=data.recent_decisions||[], admin=data.capabilities?.manage;return `<section class="m329-center" data-m329><div class="m329-hero"><div><span class="eyebrow">M32.9 · Gobierno de contacto</span><h2>Consentimientos, preferencias y supresiones</h2><p>${esc(data.notice||'')}</p></div><div class="m329-actions"><button class="btn secondary" data-m329-action="evaluate">Evaluar contacto</button></div></div><div class="m329-kpis"><article><small>Relaciones</small><b>${esc(m.relationships||0)}</b><span>Acreditadas</span></article><article><small>Autorizaciones</small><b>${esc(m.granted_preferences||0)}</b><span>Concedidas</span></article><article><small>Negativas</small><b>${esc(m.denied_preferences||0)}</b><span>Registradas</span></article><article class="danger"><small>Supresiones</small><b>${esc(m.active_suppressions||0)}</b><span>Activas</span></article><article><small>Bloqueos</small><b>${esc(m.blocked_decisions||0)}</b><span>Decisiones</span></article><article><small>Cadena</small><b>${data.audit?.valid?'Íntegra':'INVÁLIDA'}</b><span>${esc(data.audit?.events||0)} eventos</span></article></div><div class="m329-grid"><article class="card"><div class="card-header"><div><h3>Decisiones recientes</h3><p>Un resultado permitido no constituye por sí solo conclusión jurídica.</p></div></div>${decisions.length?decisions.map(decisionItem).join(''):'<p class="m329-empty">Aún no existen decisiones M32.9.</p>'}</article><article class="card"><div class="card-header"><div><h3>Avisos versionados</h3><p>${esc(data.notices?.notice||'')}</p></div></div>${notices(data.notices)}<div class="m329-warning">Las direcciones completas, evidencias originales y documentos del expediente no se guardan en esta bitácora.</div></article></div>${admin?`<details class="m329-admin"><summary>Administración de preferencias</summary><div class="m329-admin-grid">${relationshipForm()}${preferenceForm()}${suppressionForm()}${policyForm(data.policy)}${noticeForm()}</div></details>`:''}</section>`;}

async function render(force=false){if(!professional()||!currentPath().startsWith(ROUTE)||cache.loading)return;if(currentPath()!==ROUTE)return;cache.loading=true;try{if(force||!cache.dashboard)cache.dashboard=await api(BASE);document.querySelectorAll('.m329-center').forEach(node=>node.remove());const anchor=document.querySelector('.m328-center')||document.querySelector('.m327-center');if(anchor)anchor.insertAdjacentHTML('afterend',dashboard(cache.dashboard));}catch(error){toast(error.message||String(error),'danger');}finally{cache.loading=false;}}
function schedule(force=false){clearTimeout(timer);timer=setTimeout(()=>render(force),220);}

async function handleForm(form){const kind=form.dataset.m329Form,data=Object.fromEntries(new FormData(form).entries());const button=form.querySelector('button[type="submit"]');if(button)button.disabled=true;try{if(kind==='relationship')await post(`${BASE}/relationships`,{subject_id:data.subject_id,relationship_type:data.relationship_type,lawful_basis:data.lawful_basis,status:'active',evidence_reference:data.evidence_reference});if(kind==='preference')await post(`${BASE}/preferences`,{subject_id:data.subject_id,purpose:data.purpose,channel:data.channel,state:data.state,basis:data.basis,evidence_reference:data.evidence_reference,reason:data.reason});if(kind==='suppression')await post(`${BASE}/suppressions`,{subject_id:data.subject_id,scope:data.scope,channel:data.channel||null,purpose:data.purpose||null,reason:data.reason,source:'verified_request'});if(kind==='policy')await post(`${BASE}/policy`,{weekday_open:data.weekday_open,weekday_close:data.weekday_close,saturday_open:data.saturday_open,saturday_close:data.saturday_close,holidays:String(data.holidays||'').split(',').map(value=>value.trim()).filter(Boolean),max_contacts_per_day:Number(data.max_contacts_per_day),max_channels_per_7_days:Number(data.max_channels_per_7_days)});if(kind==='notice')await post(`${BASE}/notices`,{notice_id:'contact-governance',name:data.name,text:data.text});cache.dashboard=null;toast('Actuación M32.9 registrada.');await render(true);}finally{if(button)button.disabled=false;}}

document.addEventListener('submit',event=>{const form=event.target.closest('[data-m329-form]');if(!form)return;event.preventDefault();handleForm(form).catch(error=>toast(error.message||String(error),'danger'));});
document.addEventListener('click',event=>{const button=event.target.closest('[data-m329-action]');if(!button)return;event.preventDefault();button.disabled=true;let task;if(button.dataset.m329Action==='activate')task=post(`${BASE}/notices/${encodeURIComponent(button.dataset.notice)}/${encodeURIComponent(button.dataset.version)}/activate`,{});if(button.dataset.m329Action==='evaluate'){const subject_id=window.prompt('ID del titular:')||'';const purpose=window.prompt('Finalidad: professional_operational, service_transactional, commercial_marketing o collections','professional_operational')||'';const channel=window.prompt('Canal: email, sms, whatsapp o phone','email')||'';task=post(`${BASE}/evaluate`,{subject_id,purpose,channel,context_reference:'manual-ui'});}if(!task){button.disabled=false;return;}task.then(()=>{cache.dashboard=null;toast('Gobierno de contacto actualizado.');return render(true);}).catch(error=>toast(error.message||String(error),'danger')).finally(()=>button.disabled=false);});
window.addEventListener('hashchange',()=>{cache.dashboard=null;schedule(true);});
window.addEventListener('DOMContentLoaded',()=>schedule(true));
new MutationObserver(()=>{if(currentPath()===ROUTE&&!cache.loading&&!document.querySelector('.m329-center'))schedule(false);}).observe(document.getElementById('app'),{childList:true,subtree:true});
schedule(true);
