import { api, app, esc, money } from '../core.js';

export function createGoldPublicExperience() {
  function publicSiteHeader() {
    return `<header class="public-header m29-public-header public-detail-header" aria-label="Navegación pública"><button class="public-brand" type="button" data-action="go" data-route="/" aria-label="Ir al inicio"><img src="/assets/logo-legalaizit-web.png" alt="LegalAIZ.it"></button><nav class="public-nav m29-public-nav" aria-label="Navegación"><button data-action="go" data-route="/soluciones">Soluciones</button><button data-action="go" data-route="/como-funciona">Cómo funciona</button><button data-action="go" data-route="/confianza">Confianza</button></nav><div class="public-detail-nav"><button class="btn ghost" type="button" data-action="go" data-route="/soluciones">Ver otras soluciones</button><button class="btn gold" type="button" data-action="go" data-route="/login">Ingresar</button></div></header>`;
  }
  function publicFooter(){return `<footer class="public-footer m29-public-footer"><div class="m29-footer-brand"><img src="/assets/logo-legalaizit-web.png" alt="LegalAIZ.it"><p>Más que respuestas, soluciones.</p><small>Tu solución legal, impulsada por IA y expertos.</small></div><div><b>Explora</b><button data-action="go" data-route="/soluciones">Soluciones</button><button data-action="go" data-route="/como-funciona">Cómo funciona</button><button data-action="go" data-route="/confianza">Confianza</button></div><div><b>Para ti</b><button data-action="go" data-route="/para-personas">Personas</button><button data-action="go" data-route="/para-empresas">Empresas</button><button data-action="go" data-route="/preguntas-frecuentes">Preguntas frecuentes</button></div><div><b>Uso responsable</b><span>La orientación y los borradores no garantizan resultados ni sustituyen representación judicial.</span></div></footer>`;}
  function publicGoldPrecheck(gold) {
    const precheck = gold?.config?.precheck; if (!precheck) return '';
    return `<section class="public-product-section public-precheck-section" id="prediagnostico"><div class="public-section-heading"><span class="public-kicker dark">Orientación inicial sin registro</span><h2>Revisa si esta solución puede encajar con tu situación.</h2><p>${esc(precheck.intro)}</p></div><form id="public-precheck-form" class="public-precheck-form" data-code="${esc(gold.product_code)}">${precheck.questions.map((q,i)=>`<fieldset><legend><span>${i+1}</span>${esc(q.label)}</legend><div class="public-precheck-options">${q.options.map(option=>`<label><input type="radio" name="${esc(q.id)}" value="${esc(option)}" required><span>${esc(option)}</span></label>`).join('')}</div></fieldset>`).join('')}<div class="public-precheck-actions"><button class="btn gold" type="submit">Ver orientación preliminar</button><span>No pedimos nombres, identificaciones ni documentos.</span></div></form><div id="public-precheck-result" class="public-precheck-result hidden" aria-live="polite"></div></section>`;
  }
  async function publicProductPage(code) {
    let detail; try { detail=await api(`/api/public/products/${encodeURIComponent(code)}`); } catch(error){return publicNotFoundPage(error.message);}
    let gold=null; try { gold=await api(`/api/public/gold-standard/${encodeURIComponent(code)}`); } catch {}
    const product=detail.product||{}, exp=detail.experience||{}, cfg=gold?.config||{};
    const steps=exp.steps||[], deliverables=exp.deliverables||product.documents||product.outcomes||[], included=cfg.included||deliverables, excluded=cfg.not_included||product.not_included||product.exclusions||[], faq=exp.faqs||[];
    const priceAuto=Number(product.price_auto||0), priceReview=Number(product.price_review||0);
    const priceHtml=(priceAuto||priceReview)?`<div class="public-price-row">${priceAuto?`<div><small>Documento personalizado desde</small><b>${money(priceAuto)}</b></div>`:''}${priceReview?`<div><small>Con revisión profesional desde</small><b>${money(priceReview)}</b></div>`:''}</div><p>El valor definitivo se confirma antes de continuar y depende del alcance seleccionado.</p>`:'';
    document.title=`${product.title||'Solución'} · LegalAIZ.it`;
    app.innerHTML=`<div class="public-site public-product-site m29-public-site">${publicSiteHeader()}<main id="main-content" tabindex="-1">
      <section class="public-product-hero m29-product-hero"><div class="public-product-copy"><div class="public-product-breadcrumb"><button data-action="go" data-route="/">Inicio</button><span>›</span><button data-action="go" data-route="/soluciones">Soluciones</button><span>›</span><span>${esc(product.vertical||'Solución jurídica')}</span></div><div class="public-product-labels"><span class="public-category">${esc(product.vertical||'')}</span><span class="m29-guided-badge">Solución guiada</span></div><h1>${esc(product.title||code)}</h1><p>${esc(cfg.headline||exp.promise||product.summary||'')}</p><div class="public-product-actions"><button class="btn gold" data-action="go" data-route="/login">Comenzar esta solución</button>${gold?'<button class="btn public-outline" data-public-target="prediagnostico">Revisar si me sirve</button>':''}</div><div class="public-product-trust"><span>Preguntas paso a paso</span><span>Puedes guardar el avance</span><span>Revisión según riesgo</span></div></div><aside class="public-product-summary-card m29-product-summary"><img src="/assets/brand-visuals/product-${String(code).toLowerCase()}.svg" alt=""><span class="public-kicker">Al terminar puedes obtener</span><h2>${esc(deliverables[0]||'Un resultado jurídico personalizado')}</h2><ul>${deliverables.slice(0,5).map(item=>`<li>${esc(item)}</li>`).join('')}</ul>${priceHtml}</aside></section>
      <section class="m29-product-value-strip"><div><b>Te guiamos</b><span>No necesitas conocer el nombre técnico.</span></div><div><b>Personalizamos</b><span>El contenido cambia con tus respuestas.</span></div><div><b>Te advertimos</b><span>Riesgos y datos faltantes son visibles.</span></div><div><b>Conservamos</b><span>Historial, documentos y decisiones.</span></div></section>
      <section class="public-product-section"><div class="public-section-heading"><span class="public-kicker dark">Qué ocurrirá</span><h2>Un proceso comprensible de principio a fin.</h2><p>${esc(exp.promise||'Completa la información, revisa el alcance y continúa con una ruta documentada.')}</p></div><div class="public-product-steps">${steps.map((step,index)=>`<article><span>${String(step.number||index+1).padStart(2,'0')}</span><h3>${esc(step.title)}</h3><p>${esc(step.description)}</p></article>`).join('')}</div></section>
      <section class="public-product-section public-included-section"><div class="public-included-grid"><article><span class="public-kicker dark">Qué incluye</span><h2>Más que un formato para llenar.</h2><ul class="public-check-list">${included.map(item=>`<li>${esc(item)}</li>`).join('')}</ul></article><article class="public-limit-card"><span class="public-kicker">Cuándo necesitas ayuda adicional</span><h2>Límites claros antes de actuar.</h2><ul>${excluded.map(item=>`<li>${esc(item)}</li>`).join('')}</ul><p>${esc(exp.human_review?.reason||'Los hechos y riesgos del caso pueden exigir revisión profesional específica.')}</p></article></div></section>
      ${publicGoldPrecheck(gold)}
      ${cfg.legal_basis?.length?`<section class="public-product-section public-legal-basis"><div class="public-section-heading"><span class="public-kicker dark">Qué revisa la plataforma</span><h2>Aspectos jurídicos que pueden cambiar el resultado.</h2><p>Las reglas y fuentes se convierten en preguntas y alertas para que no omitas información relevante.</p></div><div class="public-basis-grid">${cfg.legal_basis.slice(0,6).map(item=>`<article><h3>${esc(item.title)}</h3><p>${esc(item.focus)}</p></article>`).join('')}</div></section>`:''}
      ${faq.length?`<section class="public-product-section public-faq"><div class="public-section-heading"><span class="public-kicker dark">Preguntas frecuentes</span><h2>Antes de comenzar.</h2></div><div class="public-faq-list">${faq.map(item=>`<details><summary>${esc(item.question)}</summary><p>${esc(item.answer)}</p></details>`).join('')}</div></section>`:''}
      <section class="public-final-cta"><div><span class="public-kicker">Más que respuestas, soluciones.</span><h2>Continúa en un espacio seguro y trazable.</h2><p>Completa la información, guarda tu avance y gestiona los documentos dentro de tu expediente.</p></div><div><button class="btn gold" data-action="go" data-route="/login">Comenzar esta solución</button><button class="btn public-outline-light" data-action="go" data-route="/soluciones">Explorar otra solución</button></div></section>
    </main>${publicFooter()}</div>`;
    document.querySelectorAll('[data-public-target]').forEach(button=>button.addEventListener('click',()=>document.getElementById(button.dataset.publicTarget||'')?.scrollIntoView({behavior:'smooth',block:'start'})));
    document.getElementById('public-precheck-form')?.addEventListener('submit',publicPrecheckSubmit);
  }
  async function publicPrecheckSubmit(event){event.preventDefault();const form=event.currentTarget,output=document.getElementById('public-precheck-result'),button=event.submitter,answers=Object.fromEntries(new FormData(form).entries());button.disabled=true;button.textContent='Revisando…';try{const result=await api('/api/public/gold-precheck',{method:'POST',body:JSON.stringify({product_code:form.dataset.code,answers})});const alerts=(result.alerts||[]).map(item=>`<li>${esc(item.message)}</li>`).join('');output.className=`public-precheck-result ${esc(result.risk)}`;output.innerHTML=`<div class="public-precheck-result-head"><span>${result.risk==='green'?'✓':result.risk==='red'?'!':'i'}</span><div><small>Orientación preliminar</small><h3>${esc(result.label)}</h3></div></div>${alerts?`<ul>${alerts}</ul>`:'<p>No se detectaron alertas en este filtro inicial. El formulario completo puede identificar otras condiciones.</p>'}<div class="public-precheck-next"><p>${esc(result.next_action)}</p><button class="btn navy" data-action="go" data-route="/login">Continuar con cuenta segura</button></div><small>${esc(result.disclaimer)}</small>`;}catch(error){output.className='public-precheck-result red';output.innerHTML=`<p>${esc(error.message)}</p>`;}finally{button.disabled=false;button.textContent='Ver orientación preliminar';}}
  function publicNotFoundPage(message='No encontramos esta solución.'){app.innerHTML=`<div class="public-site">${publicSiteHeader()}<main class="public-not-found"><h1>Solución no disponible</h1><p>${esc(message)}</p><button class="btn gold" data-action="go" data-route="/soluciones">Volver a soluciones</button></main>${publicFooter()}</div>`;}
  return {publicProductPage,publicNotFoundPage};
}
