'use strict';

import { api, closeDialog, dateText, esc, humanize, openDialog, state, toast } from '../core.js';

const endpoint = '/api/m30/governance';
const productNames = {'CO-LA-002':'Contrato laboral','CO-EM-003':'Prestación de servicios','CO-AR-001':'Arrendamiento','CO-CD-003':'Protección al consumidor'};
const statusTone = value => ['closed','acknowledged','executed','approved','recovered'].includes(value) ? 'green' : ['critical','high','blocked_legal_hold','report_overdue'].includes(value) ? 'red' : ['exported','pending_qa','triaged','monitoring'].includes(value) ? 'blue' : 'yellow';
const badge = value => `<span class="badge ${statusTone(value)}">${esc(humanize(value))}</span>`;
const option = (value,label,selected=false) => `<option value="${esc(value)}"${selected?' selected':''}>${esc(label)}</option>`;
const val = id => document.getElementById(id)?.value || '';
const checked = id => Boolean(document.getElementById(id)?.checked);

function communicationSection(data, participantData) {
  const rows=data.communications||[], metrics=data.communication_metrics||{}, participants=(participantData?.participants||[]).filter(p=>['invited','accepted','withdrawn'].includes(p.status));
  const participantOptions=participants.map(p=>option(p.id,`${p.user_name} · ${productNames[p.product_code]||p.product_code}`)).join('');
  return `<section class="card m303-card"><div class="card-header"><div><span class="eyebrow">Comunicaciones controladas</span><h2>Avisos sin narrar el caso</h2><p>La plataforma prepara mensajes dentro de la cuenta o para exportación manual. El envío externo continúa deshabilitado.</p></div><div class="button-group"><button class="btn primary sm" type="button" data-m303-communication>Preparar aviso</button><a class="btn secondary sm" href="${endpoint}/export" download>Exportar gobernanza</a></div></div><div class="m303-kpis"><div><span>Listos</span><b>${esc(metrics.ready||0)}</b></div><div><span>Exportados</span><b>${esc(metrics.exported||0)}</b></div><div><span>Confirmados</span><b>${esc(metrics.acknowledged||0)}</b></div></div>${rows.length?`<div class="m303-list">${rows.slice(0,10).map(row=>`<article><div><div class="approval-badges">${badge(row.status)}<span class="badge blue">${esc(humanize(row.template_code))}</span></div><b>${esc(row.subject)}</b><small>${esc(row.user_name||'Cohorte')} · ${esc(row.masked_email||'sin correo')} · ${esc(dateText(row.created_at))}</small></div>${row.status==='ready'?`<button class="btn ghost sm" type="button" data-m303-communication-state="${esc(row.id)}" data-status="exported">Marcar exportado</button>`:''}</article>`).join('')}</div>`:'<div class="empty-state compact"><p>No hay comunicaciones preparadas.</p></div>'}<template id="m303-participant-options">${participantOptions}</template></section>`;
}

function incidentSection(data) {
  const rows=data.incidents||[], metrics=data.incident_metrics||{};
  return `<section class="card m303-card"><div class="card-header"><div><span class="eyebrow">Incidentes y privacidad</span><h2>Contención, evidencia y reporte</h2><p>El plazo regulatorio se calcula como ayuda operativa y debe verificarse con festivos, hechos y canal aplicable.</p></div><button class="btn primary sm" type="button" data-m303-incident>Registrar incidente</button></div><div class="m303-kpis four"><div><span>Abiertos</span><b>${esc(metrics.open||0)}</b></div><div><span>Graves</span><b>${esc(metrics.high_or_critical_open||0)}</b></div><div><span>Evaluación pendiente</span><b>${esc(metrics.regulatory_pending||0)}</b></div><div><span>Reportes vencidos</span><b>${esc(metrics.report_overdue||0)}</b></div></div>${rows.length?`<div class="m303-list">${rows.slice(0,12).map(row=>`<article class="${row.report_overdue?'is-alert':''}"><div><div class="approval-badges">${badge(row.severity)}${badge(row.status)}${row.legal_hold?'<span class="badge red">Legal hold</span>':''}${row.report_overdue?'<span class="badge red">Reporte vencido</span>':''}</div><b>${esc(row.title)}</b><small>${esc(humanize(row.category))} · ${esc(humanize(row.containment_status||'not_started'))}${row.report_due_at?` · límite operativo ${esc(dateText(row.report_due_at))}`:''}</small></div>${state.user.role==='admin'?`<button class="btn secondary sm" type="button" data-m303-manage-incident="${esc(row.id)}">Gestionar</button>`:''}</article>`).join('')}</div>`:'<div class="empty-state compact"><p>No hay incidentes registrados.</p></div>'}</section>`;
}

function retentionSection(data) {
  const candidates=data.retention_candidates||[], requests=data.retention_requests||[];
  const requestMap=Object.fromEntries(requests.map(r=>[r.participant_id,r]));
  return `<section class="card m303-card"><div class="card-header"><div><span class="eyebrow">Retención y depuración</span><h2>Finalidad, plazo y doble aprobación</h2><p>Los expedientes y documentos jurídicos están fuera de esta depuración. Solo se gestionan registros operativos del piloto.</p></div></div>${candidates.length?`<div class="m303-retention-list">${candidates.map(row=>{const req=requestMap[row.participant_id]; return `<article><div><div class="approval-badges">${badge(row.participant_status)}${row.legal_hold?'<span class="badge red">Legal hold</span>':''}${req?badge(req.status):''}</div><b>${esc(row.user_name)} · ${esc(productNames[row.product_code]||row.product_code)}</b><small>${esc(humanize(row.action_type))} · fecha ${esc(dateText(row.due_at))}</small></div><div class="button-group">${!req&&state.user.role==='admin'?`<button class="btn secondary sm" data-m303-retention-create="${esc(row.participant_id)}">Crear solicitud</button>`:''}${req?.status==='pending_legal'&&state.user.role==='specialist'?`<button class="btn primary sm" data-m303-retention-approve="${esc(req.id)}" data-stage="legal">Aprobar jurídico</button>`:''}${req?.status==='pending_qa'&&state.user.role==='admin'?`<button class="btn primary sm" data-m303-retention-approve="${esc(req.id)}" data-stage="qa">Aprobar QA</button>`:''}${req?.status==='approved'&&state.user.role==='admin'?`<button class="btn danger sm" data-m303-retention-execute="${esc(req.id)}">Ejecutar</button>`:''}</div></article>`}).join('')}</div>`:'<div class="empty-state compact"><p>No hay registros elegibles para depuración terminal.</p></div>'}<div class="legal-notice mt-16"><b>Sin eliminación automática.</b> La ejecución irreversible requiere fecha cumplida, ausencia de legal hold, especialista jurídico y QA distintos.</div></section>`;
}

function closureSection(data) {
  const gate=data.closure_gate||{}, closures=data.closures||[], latest=closures[0];
  return `<section class="card m303-card"><div class="card-header"><div><span class="eyebrow">Cierre de cohorte</span><h2>Decisión sustentada y reversible hasta ejecutar</h2><p>El cierre no autoriza producción pública. Preserva la evidencia, programa retención y comunica a participantes.</p></div>${state.user.role==='admin'&&data.active_cohort?'<button class="btn primary sm" type="button" data-m303-closure>Preparar cierre</button>':''}</div><progress class="m30-progress" max="${esc(gate.total||1)}" value="${esc(gate.passed||0)}">${esc(gate.passed||0)}/${esc(gate.total||1)}</progress><div class="m30-check-grid">${Object.entries(gate.checks||{}).map(([key,ok])=>`<div class="m30-check ${ok?'ok':''}"><span>${ok?'✓':'○'}</span><b>${esc(humanize(key))}</b></div>`).join('')}</div>${latest?`<div class="m303-closure-state"><div><div class="approval-badges">${badge(latest.status)}${badge(latest.decision)}</div><b>${esc(humanize(latest.reason_code))}</b><small>${esc(latest.summary)} · ${esc(dateText(latest.created_at))}</small></div><div class="button-group">${latest.status==='pending_legal'&&state.user.role==='specialist'?`<button class="btn primary sm" data-m303-closure-approve="${esc(latest.id)}" data-stage="legal">Aprobar jurídico</button>`:''}${latest.status==='pending_qa'&&state.user.role==='admin'?`<button class="btn primary sm" data-m303-closure-approve="${esc(latest.id)}" data-stage="qa">Aprobar QA</button>`:''}${latest.status==='approved'&&state.user.role==='admin'?`<button class="btn danger sm" data-m303-closure-execute="${esc(latest.id)}">Cerrar cohorte</button>`:''}</div></div>`:'<div class="empty-state compact mt-16"><p>Aún no existe una decisión formal de cierre.</p></div>'}</section>`;
}

export function governanceProfessionalSection(data, participantData) {
  if(!data) return '';
  return `<section class="m303-governance"><div class="m303-hero"><div><span class="eyebrow">M30.3 · gobierno del piloto</span><h2>Comunicar, contener, conservar y cerrar</h2><p>${esc(data.notice)}</p></div><img src="/assets/brand-visuals/pilot/governance.svg" alt="Gobernanza, incidentes y cierre del piloto LegalAIZ.it"></div><div class="section-grid mt-16"><div class="span-6">${communicationSection(data,participantData)}</div><div class="span-6">${incidentSection(data)}</div><div class="span-7">${retentionSection(data)}</div><div class="span-5">${closureSection(data)}</div></div></section>`;
}

export function bindGovernanceProfessional(data, participantData, refresh) {
  document.querySelector('[data-m303-communication]')?.addEventListener('click',()=>communicationDialog(data,participantData,refresh));
  document.querySelectorAll('[data-m303-communication-state]').forEach(button=>button.addEventListener('click',()=>post(`${endpoint}/communications/${encodeURIComponent(button.dataset.m303CommunicationState)}`,{status:button.dataset.status},refresh,'Comunicación actualizada.')));
  document.querySelector('[data-m303-incident]')?.addEventListener('click',()=>incidentDialog(data,refresh));
  document.querySelectorAll('[data-m303-manage-incident]').forEach(button=>button.addEventListener('click',()=>incidentManageDialog(data,button.dataset.m303ManageIncident,refresh)));
  document.querySelectorAll('[data-m303-retention-create]').forEach(button=>button.addEventListener('click',()=>post(`${endpoint}/retention`,{participant_id:button.dataset.m303RetentionCreate,rationale_code:'purpose_completed'},refresh,'Solicitud de retención creada.')));
  document.querySelectorAll('[data-m303-retention-approve]').forEach(button=>button.addEventListener('click',()=>approvalDialog('retention',button.dataset.m303RetentionApprove,button.dataset.stage,data,refresh)));
  document.querySelectorAll('[data-m303-retention-execute]').forEach(button=>button.addEventListener('click',()=>executionDialog('retention',button.dataset.m303RetentionExecute,data,refresh)));
  document.querySelector('[data-m303-closure]')?.addEventListener('click',()=>closureDialog(data,refresh));
  document.querySelectorAll('[data-m303-closure-approve]').forEach(button=>button.addEventListener('click',()=>approvalDialog('closures',button.dataset.m303ClosureApprove,button.dataset.stage,data,refresh)));
  document.querySelectorAll('[data-m303-closure-execute]').forEach(button=>button.addEventListener('click',()=>executionDialog('closures',button.dataset.m303ClosureExecute,data,refresh)));
}

function communicationDialog(data,participantData,refresh){
  const templates=data.policy.communication_templates||{}, participants=(participantData?.participants||[]).filter(p=>['invited','accepted','withdrawn'].includes(p.status));
  openDialog({title:'Preparar comunicación',subtitle:'Se publica dentro de la cuenta o queda lista para exportación manual.',body:`<div class="field"><label for="m303-template">Tipo de aviso</label><select id="m303-template" class="select">${Object.entries(templates).map(([k,v])=>option(k,v.label)).join('')}</select></div><div class="field"><label for="m303-participant">Participante</label><select id="m303-participant" class="select"><option value="">Toda la cohorte, solo para cierre</option>${participants.map(p=>option(p.id,`${p.user_name} · ${productNames[p.product_code]||p.product_code}`)).join('')}</select></div><div class="legal-notice"><b>Canal controlado.</b> No se envían correos desde esta versión y no se incluyen hechos jurídicos.</div>`,actions:'<button class="btn secondary" type="button" data-action="close-dialog">Cancelar</button><button class="btn primary" id="m303-save-communication" type="button">Preparar aviso</button>'});
  document.getElementById('m303-save-communication')?.addEventListener('click',()=>post(`${endpoint}/communications`,{template_code:val('m303-template'),participant_id:val('m303-participant'),channel:'account'},refresh,'Comunicación preparada.'));
}

function incidentDialog(data,refresh){
  const p=data.policy.incident;
  openDialog({title:'Registrar incidente',subtitle:'Describe el evento operativo sin copiar documentos ni relatar el caso.',body:`<div class="m30-dialog-grid"><div class="field"><label for="m303-incident-category">Categoría</label><select id="m303-incident-category" class="select">${p.categories.map(x=>option(x,humanize(x))).join('')}</select></div><div class="field"><label for="m303-incident-severity">Severidad inicial</label><select id="m303-incident-severity" class="select">${['low','medium','high','critical'].map(x=>option(x,humanize(x))).join('')}</select></div></div><div class="field"><label for="m303-incident-title">Título</label><input id="m303-incident-title" class="input" maxlength="160"></div><div class="field"><label for="m303-incident-description">Descripción minimizada</label><textarea id="m303-incident-description" class="textarea" maxlength="2000"></textarea></div><label class="check-line"><input id="m303-personal-data" type="checkbox"> Existe afectación o sospecha sobre datos personales</label><div class="field"><label for="m303-data-class">Clase principal de datos</label><select id="m303-data-class" class="select">${p.data_classes.map(x=>option(x,humanize(x))).join('')}</select></div><div class="field"><label for="m303-record-bucket">Registros potencialmente afectados</label><select id="m303-record-bucket" class="select">${p.affected_record_buckets.map(x=>option(x,humanize(x))).join('')}</select></div>`,actions:'<button class="btn secondary" type="button" data-action="close-dialog">Cancelar</button><button class="btn primary" id="m303-save-incident" type="button">Registrar incidente</button>'});
  document.getElementById('m303-save-incident')?.addEventListener('click',()=>post(`${endpoint}/incidents`,{category:val('m303-incident-category'),severity:val('m303-incident-severity'),title:val('m303-incident-title'),description:val('m303-incident-description'),personal_data_affected:checked('m303-personal-data'),data_classes:[val('m303-data-class')],affected_records_bucket:val('m303-record-bucket')},refresh,'Incidente registrado.'));
}

function incidentManageDialog(data,id,refresh){
  const row=(data.incidents||[]).find(x=>x.id===id), p=data.policy.incident;
  openDialog({title:'Gestionar incidente',subtitle:row?.title||'Incidente',body:`<div class="m30-dialog-grid"><div class="field"><label for="m303-status">Estado</label><select id="m303-status" class="select">${['open','triaged','mitigated','closed'].map(x=>option(x,humanize(x),x===row.status)).join('')}</select></div><div class="field"><label for="m303-containment">Contención</label><select id="m303-containment" class="select">${p.containment_statuses.map(x=>option(x,humanize(x),x===row.containment_status)).join('')}</select></div><div class="field"><label for="m303-assessment">Evaluación regulatoria</label><select id="m303-assessment" class="select">${p.regulatory_assessments.map(x=>option(x,humanize(x),x===row.regulatory_assessment)).join('')}</select></div><div class="field"><label for="m303-channel">Canal de reporte</label><select id="m303-channel" class="select"><option value="">Pendiente</option>${p.reporting_channels.map(x=>option(x,humanize(x),x===row.reporting_channel)).join('')}</select></div><div class="field"><label for="m303-root-cause">Causa raíz</label><select id="m303-root-cause" class="select">${p.root_cause_codes.map(x=>option(x,humanize(x),x===row.root_cause_code)).join('')}</select></div><div class="field"><label for="m303-reported-at">Fecha de reporte</label><input id="m303-reported-at" type="datetime-local" class="input"></div></div><label class="check-line"><input id="m303-legal-hold" type="checkbox" ${row.legal_hold?'checked':''}> Preservar por legal hold</label><div class="field"><label for="m303-assessment-note">Nota verificable</label><textarea id="m303-assessment-note" class="textarea" maxlength="1500">${esc(row.assessment_note||row.resolution_note||'')}</textarea></div><div class="legal-notice"><b>Plazo operativo:</b> ${esc(row.report_due_at?dateText(row.report_due_at):'no calculado')}. ${esc(p.deadline_note)}</div>`,actions:'<button class="btn secondary" type="button" data-action="close-dialog">Cancelar</button><button class="btn primary" id="m303-save-triage" type="button">Actualizar incidente</button>'});
  document.getElementById('m303-save-triage')?.addEventListener('click',()=>post(`${endpoint}/incidents/${encodeURIComponent(id)}`,{status:val('m303-status'),containment_status:val('m303-containment'),regulatory_assessment:val('m303-assessment'),reporting_channel:val('m303-channel'),reported_at:val('m303-reported-at'),root_cause_code:val('m303-root-cause'),legal_hold:checked('m303-legal-hold'),assessment_note:val('m303-assessment-note'),resolution_note:val('m303-assessment-note')},refresh,'Incidente actualizado.'));
}

function approvalDialog(kind,id,stage,data,refresh){
  const isRetention=kind==='retention';
  const key=stage==='legal'?(isRetention?'legal_retention_approval':'legal_closure_approval'):(isRetention?'qa_retention_approval':'qa_closure_approval');
  const phrase=data.policy.confirmations[key];
  openDialog({title:stage==='legal'?'Aprobación jurídica':'Aprobación QA',subtitle:'La aprobación queda vinculada a la identidad y no puede coincidir con la otra etapa.',body:`<div class="field"><label for="m303-approval-confirmation">Confirmación</label><input id="m303-approval-confirmation" class="input" placeholder="${esc(phrase)}"></div>`,actions:'<button class="btn secondary" type="button" data-action="close-dialog">Cancelar</button><button class="btn primary" id="m303-confirm-approval" type="button">Aprobar</button>'});
  document.getElementById('m303-confirm-approval')?.addEventListener('click',()=>post(`${endpoint}/${kind}/${encodeURIComponent(id)}/approve`,{stage,confirmation:val('m303-approval-confirmation')},refresh,'Aprobación registrada.'));
}

function executionDialog(kind,id,data,refresh){
  const isRetention=kind==='retention', phrase=data.policy.confirmations[isRetention?'execute_retention':'execute_closure'];
  openDialog({title:isRetention?'Ejecutar depuración':'Cerrar cohorte',subtitle:'Esta acción exige controles completos y deja evidencia inmutable.',body:`<div class="legal-notice"><b>Acción sensible.</b> Verifica fecha, legal hold, aprobaciones y alcance antes de continuar.</div><div class="field mt-16"><label for="m303-execution-confirmation">Confirmación</label><input id="m303-execution-confirmation" class="input" placeholder="${esc(phrase)}"></div>`,actions:'<button class="btn secondary" type="button" data-action="close-dialog">Cancelar</button><button class="btn danger" id="m303-confirm-execution" type="button">Ejecutar</button>'});
  document.getElementById('m303-confirm-execution')?.addEventListener('click',()=>post(`${endpoint}/${kind}/${encodeURIComponent(id)}/execute`,{confirmation:val('m303-execution-confirmation')},refresh,isRetention?'Depuración ejecutada.':'Cohorte cerrada.'));
}

function closureDialog(data,refresh){
  const closure=data.policy.closure;
  openDialog({title:'Preparar decisión de cierre',subtitle:'El cierre exige compuertas completas y dos aprobaciones distintas.',body:`<div class="m30-dialog-grid"><div class="field"><label for="m303-closure-decision">Decisión</label><select id="m303-closure-decision" class="select">${closure.decisions.map(x=>option(x,humanize(x))).join('')}</select></div><div class="field"><label for="m303-closure-reason">Motivo</label><select id="m303-closure-reason" class="select">${closure.reason_codes.map(x=>option(x,humanize(x))).join('')}</select></div></div><div class="field"><label for="m303-closure-summary">Síntesis verificable</label><textarea id="m303-closure-summary" class="textarea" maxlength="1200"></textarea></div>`,actions:'<button class="btn secondary" type="button" data-action="close-dialog">Cancelar</button><button class="btn primary" id="m303-save-closure" type="button">Preparar decisión</button>'});
  document.getElementById('m303-save-closure')?.addEventListener('click',()=>post(`${endpoint}/closures`,{decision:val('m303-closure-decision'),reason_code:val('m303-closure-reason'),summary:val('m303-closure-summary')},refresh,'Decisión preparada.'));
}

async function post(url,body,refresh,message){
  try{await api(url,{method:'POST',body:JSON.stringify(body)}); closeDialog(); toast(message); await refresh();}
  catch(error){toast(error.message,'danger');}
}

export function clientCommunicationSection(data){
  const rows=data?.communications||[];
  if(!rows.length) return '';
  return `<section class="card m303-client-communications"><div class="card-header"><div><span class="eyebrow">Comunicaciones del piloto</span><h2>Avisos disponibles en tu cuenta</h2><p>${esc(data.notice||'')}</p></div></div><div class="m303-list">${rows.map(row=>`<article><div><div class="approval-badges">${badge(row.status)}</div><b>${esc(row.subject)}</b><p>${esc(row.body)}</p><small>${esc(dateText(row.created_at))}</small></div>${row.status!=='acknowledged'?`<button class="btn secondary sm" data-m303-client-ack="${esc(row.id)}">Marcar como leído</button>`:''}</article>`).join('')}</div></section>`;
}

export function bindClientCommunications(data,refresh){
  document.querySelectorAll('[data-m303-client-ack]').forEach(button=>button.addEventListener('click',async()=>{try{await api(`${endpoint}/communications/${encodeURIComponent(button.dataset.m303ClientAck)}`,{method:'POST',body:JSON.stringify({status:'acknowledged'})});toast('Comunicación confirmada.');await refresh();}catch(error){toast(error.message,'danger');}}));
}
