import { api, app, esc, state, toast } from '../core.js';

const endpoint = '/api/m24/pilot-operations';
const checked = id => Boolean(document.getElementById(id)?.checked);
const value = id => document.getElementById(id)?.value || '';
const ratingOptions = Array.from({length:5},(_,i)=>`<option value="${i+1}">${i+1}</option>`).join('');

export function createPilotExperience({ shell, pageHeader }) {
  const badge = status => `<span class="badge ${status === 'passed' || status === 'active' || status === true ? 'green' : status === 'failed' || status === 'critical' || status === 'high' ? 'red' : 'yellow'}">${esc(status === true ? 'Cumple' : status === false ? 'Pendiente' : status)}</span>`;
  const progress = gate => `<div class="pilot-gate-progress"><span style="width:${Math.round((gate.passed_checks || 0) / Math.max(1, gate.total_checks || 1) * 100)}%"></span></div>`;

  function clientPage(data) {
    const enrollment = data.enrollment;
    const products = data.policy?.pilot_products || [];
    const cases = data.cases || [];
    const consent = enrollment?.status === 'consented';
    return `<div class="page">${pageHeader({eyebrow:'Piloto interno',title:'Participación controlada',description:'Prueba el recorrido con datos ficticios o minimizados y reporta claridad, facilidad e incidencias.'})}
      <div class="result-banner ${data.eligible ? 'green' : 'yellow'}"><div class="result-icon">${data.eligible ? '✓' : '!'}</div><div><h2>${data.eligible ? 'Participación habilitada' : 'Piloto aún no habilitado para tu cuenta'}</h2><p>${esc(data.notice || '')}</p></div></div>
      <section class="section-grid mt-22"><div class="card span-7"><div class="card-header"><div><h2>Consentimiento del piloto</h2><p>La participación es voluntaria y puede retirarse sin eliminar la trazabilidad ya generada.</p></div>${badge(enrollment?.status || 'sin consentimiento')}</div>
      ${consent ? `<div class="legal-notice"><b>Consentimiento vigente.</b> Versión ${esc(enrollment.consent_version)} · productos: ${(enrollment.product_codes || []).map(esc).join(', ')}</div><button class="btn secondary mt-16" data-action="pilot-withdraw">Retirar participación</button>` : `<div class="pilot-consent-list">
        <label><input id="pilot-ack-nonprod" type="checkbox"> Comprendo que es un entorno interno y no productivo.</label>
        <label><input id="pilot-ack-privacy" type="checkbox"> Usaré datos ficticios o minimizados y no incluiré información sensible innecesaria.</label>
        <label><input id="pilot-ack-representation" type="checkbox"> Comprendo que la plataforma no asume representación judicial ni garantiza resultados.</label>
        <label><input id="pilot-ack-data" type="checkbox"> Autorizo métricas técnicas minimizadas, sin conservar la narrativa inicial.</label>
      </div><div class="field mt-16"><label for="pilot-products">Productos del piloto</label><select id="pilot-products" class="select" multiple size="4">${products.map(code=>`<option value="${esc(code)}">${esc(code)}</option>`).join('')}</select></div><div class="field"><label for="pilot-confirmation">Confirmación</label><input id="pilot-confirmation" class="input" placeholder="ACEPTO PARTICIPAR EN EL PILOTO INTERNO"></div><button class="btn primary" data-action="pilot-enroll">Registrar consentimiento</button>`}</div>
      <aside class="card span-5"><div class="card-header"><div><h2>Estado operativo</h2><p>Solo se habilita cuando el producto tenga aprobación dual y activación interna.</p></div></div><div class="readiness-list"><div class="readiness-row"><div><b>Piloto global</b><span>Control administrativo</span></div>${badge(data.control?.state || 'frozen')}</div><div class="readiness-row"><div><b>Productos activos</b><span>${(data.active_products || []).join(', ') || 'Ninguno'}</span></div><span class="badge blue">${(data.active_products || []).length}</span></div><div class="readiness-row"><div><b>Retroalimentaciones</b><span>Enviadas por tu cuenta</span></div><span class="badge blue">${data.feedback_count || 0}</span></div></div></aside></section>
      ${consent ? `<section class="section-grid mt-22"><div class="card span-6"><div class="card-header"><div><h2>Evalúa una experiencia</h2><p>No incluyas nombres, identificaciones ni información clínica.</p></div></div><div class="field"><label for="pilot-feedback-case">Expediente</label><select id="pilot-feedback-case" class="select"><option value="">Experiencia general</option>${cases.map(c=>`<option value="${esc(c.id)}">${esc(c.product_code)} · ${esc(c.title)}</option>`).join('')}</select></div><div class="pilot-rating-grid"><label>Claridad<select id="pilot-feedback-clarity" class="select">${ratingOptions}</select></label><label>Facilidad<select id="pilot-feedback-ease" class="select">${ratingOptions}</select></label><label>Confianza<select id="pilot-feedback-confidence" class="select">${ratingOptions}</select></label></div><label class="check-line"><input id="pilot-feedback-goal" type="checkbox"> Logré el objetivo esperado del recorrido</label><div class="field"><label for="pilot-feedback-comment">Comentario opcional</label><textarea id="pilot-feedback-comment" class="textarea" maxlength="1000"></textarea></div><button class="btn primary" data-action="pilot-feedback">Enviar evaluación</button></div>
      <div class="card span-6"><div class="card-header"><div><h2>Reporta una incidencia</h2><p>Los datos personales se reducen automáticamente en el texto libre.</p></div></div><div class="field"><label for="pilot-incident-category">Categoría</label><select id="pilot-incident-category" class="select"><option value="usability">Usabilidad</option><option value="document">Documento</option><option value="legal_content">Contenido jurídico</option><option value="privacy">Privacidad</option><option value="security">Seguridad</option><option value="performance">Rendimiento</option><option value="other">Otra</option></select></div><div class="field"><label for="pilot-incident-title">Título</label><input id="pilot-incident-title" class="input" maxlength="160"></div><div class="field"><label for="pilot-incident-description">Descripción</label><textarea id="pilot-incident-description" class="textarea" maxlength="2000"></textarea></div><button class="btn secondary" data-action="pilot-incident">Registrar incidencia</button></div></section>` : ''}</div>`;
  }

  function professionalPage(data) {
    const gate = data.release_gate || {};
    const metrics = gate.metrics || {};
    const feedback = metrics.feedback || {};
    const checks = Object.entries(gate.checks || {});
    const manual = gate.manual_validations || [];
    const incidents = data.incidents || [];
    return `<div class="page">${pageHeader({eyebrow:'Preproducción',title:'Piloto interno y compuertas de salida',description:'Consentimiento, métricas minimizadas, incidencias, validación manual y control reversible del piloto.'})}
      <div class="result-banner ${gate.internal_pilot_ready ? 'green' : 'yellow'}"><div class="result-icon">${gate.internal_pilot_ready ? '✓' : '!'}</div><div><h2>${gate.internal_pilot_ready ? 'Piloto interno listo' : 'Salida bloqueada hasta completar controles'}</h2><p>Producción pública permanece bloqueada. M23.2 no está publicada y el checkout continúa en sandbox.</p></div></div>
      <section class="kpi-grid mt-22"><div class="kpi"><span class="kpi-label">Participantes</span><div class="kpi-value"><strong>${metrics.consented_participants || 0}</strong><span class="kpi-icon">○</span></div></div><div class="kpi"><span class="kpi-label">Casos entregados</span><div class="kpi-value"><strong>${metrics.delivered_cases || 0}</strong><span class="kpi-icon">✓</span></div></div><div class="kpi"><span class="kpi-label">Evaluaciones</span><div class="kpi-value"><strong>${feedback.count || 0}</strong><span class="kpi-icon">★</span></div></div><div class="kpi"><span class="kpi-label">Claridad promedio</span><div class="kpi-value"><strong>${feedback.average_clarity || 0}</strong><span class="kpi-icon">5</span></div></div></section>
      <section class="section-grid"><div class="card span-7"><div class="card-header"><div><h2>Compuertas verificables</h2><p>${gate.passed_checks || 0} de ${gate.total_checks || 0} controles superados.</p></div>${badge(gate.internal_pilot_ready)}</div>${progress(gate)}<div class="readiness-list mt-16">${checks.map(([key,ok])=>`<div class="readiness-row"><div><b>${esc(key.replaceAll('_',' '))}</b><span>Control automático M24.8</span></div>${badge(ok)}</div>`).join('')}</div></div>
      <aside class="card span-5"><div class="card-header"><div><h2>Control del piloto</h2><p>Congelar preserva expedientes, consentimientos, métricas y auditoría.</p></div>${badge(gate.control?.state || 'frozen')}</div><div class="button-group"><button class="btn primary" data-action="pilot-control" data-pilot-action="activate" ${data.can_govern ? '' : 'disabled'}>Activar</button><button class="btn secondary" data-action="pilot-control" data-pilot-action="freeze" ${data.can_govern ? '' : 'disabled'}>Congelar</button></div><div class="legal-notice mt-16"><b>Sin publicación automática.</b> La activación global exige al menos un producto aprobado y activado individualmente, y ausencia de incidentes altos o críticos abiertos.</div></aside></section>
      <section class="card mt-22"><div class="card-header"><div><h2>Validación manual multidispositivo</h2><p>Cada resultado requiere evidencia verificable.</p></div></div><div class="pilot-manual-grid">${manual.map(row=>`<article><div><b>${esc(row.label)}</b><span>${esc(row.evidence_note || 'Sin evidencia registrada')}</span></div>${badge(row.status)}${data.can_govern ? `<div class="button-group"><button class="btn secondary sm" data-action="pilot-manual" data-check-id="${esc(row.id)}" data-status="passed">Aprobar</button><button class="btn secondary sm" data-action="pilot-manual" data-check-id="${esc(row.id)}" data-status="blocked">Bloquear</button></div>` : ''}</article>`).join('')}</div></section>
      <section class="card mt-22"><div class="card-header"><div><h2>Incidencias</h2><p>Priorizadas por severidad y estado.</p></div><span class="badge blue">${incidents.length}</span></div>${incidents.length ? `<div class="pilot-incident-list">${incidents.map(row=>`<article><div><span class="badge ${['critical','high'].includes(row.severity)?'red':'yellow'}">${esc(row.severity)}</span><b>${esc(row.title)}</b><p>${esc(row.description)}</p><small>${esc(row.category)} · ${esc(row.status)}</small></div>${data.can_govern && row.status !== 'closed' ? `<button class="btn secondary sm" data-action="pilot-triage" data-incident-id="${esc(row.id)}">Clasificar</button>` : ''}</article>`).join('')}</div>` : '<div class="empty-state compact"><p>No hay incidencias registradas.</p></div>'}</section>
      <section class="card mt-22"><div class="card-header"><div><h2>Bloqueos para producción pública</h2><p>Estos controles no pueden omitirse mediante la activación del piloto.</p></div></div><ul class="check-list muted-checks">${(gate.public_blockers || []).map(item=>`<li>${esc(item)}</li>`).join('')}</ul></section></div>`;
  }

  async function pilotPage() {
    const data = await api(endpoint);
    app.innerHTML = shell(state.user.role === 'client' ? clientPage(data) : professionalPage(data));
  }

  async function refresh(message) { if (message) toast(message); await pilotPage(); }
  async function enroll() {
    const products = Array.from(document.getElementById('pilot-products')?.selectedOptions || []).map(option=>option.value);
    try { await api(`${endpoint}/enrollment`,{method:'POST',body:JSON.stringify({product_codes:products,non_production_ack:checked('pilot-ack-nonprod'),privacy_ack:checked('pilot-ack-privacy'),no_representation_ack:checked('pilot-ack-representation'),fictitious_or_minimized_data_ack:checked('pilot-ack-data'),confirmation:value('pilot-confirmation')})}); await refresh('Consentimiento registrado.'); } catch(error){ toast(error.message,'danger'); }
  }
  async function withdraw() { if (!confirm('¿Retirar tu participación del piloto? La auditoría ya creada se conservará.')) return; try { await api(`${endpoint}/enrollment`,{method:'POST',body:JSON.stringify({action:'withdraw'})}); await refresh('Participación retirada.'); } catch(error){ toast(error.message,'danger'); } }
  async function feedback() { try { await api(`${endpoint}/feedback`,{method:'POST',body:JSON.stringify({case_id:value('pilot-feedback-case')||null,clarity:Number(value('pilot-feedback-clarity')),ease:Number(value('pilot-feedback-ease')),confidence:Number(value('pilot-feedback-confidence')),goal_met:checked('pilot-feedback-goal'),comment:value('pilot-feedback-comment')})}); await refresh('Evaluación registrada.'); } catch(error){ toast(error.message,'danger'); } }
  async function incident() { try { await api(`${endpoint}/incidents`,{method:'POST',body:JSON.stringify({category:value('pilot-incident-category'),severity:'medium',title:value('pilot-incident-title'),description:value('pilot-incident-description')})}); await refresh('Incidencia registrada.'); } catch(error){ toast(error.message,'danger'); } }
  async function manual(checkId,status) { const note=prompt('Describe la evidencia o el bloqueo (mínimo 15 caracteres):',''); if (!note) return; try { await api(`${endpoint}/manual-validations`,{method:'POST',body:JSON.stringify({check_id:checkId,status,evidence_note:note})}); await refresh('Validación actualizada.'); } catch(error){ toast(error.message,'danger'); } }
  async function control(action) { const confirmation=prompt(action==='activate'?'Escribe ACTIVAR PILOTO OPERATIVO':'Escribe CONGELAR PILOTO Y PRESERVAR DATOS',''); if (!confirmation) return; const reason=prompt('Justificación verificable (mínimo 20 caracteres):',''); if (!reason) return; try { await api(`${endpoint}/control`,{method:'POST',body:JSON.stringify({action,confirmation,reason})}); await refresh(action==='activate'?'Piloto activado.':'Piloto congelado.'); } catch(error){ toast(error.message,'danger'); } }
  async function triage(id) { const severity=prompt('Severidad: low, medium, high o critical','medium'); const status=prompt('Estado: open, triaged, mitigated o closed','triaged'); const note=prompt('Nota de clasificación o resolución:',''); try { await api(`${endpoint}/incidents/${encodeURIComponent(id)}/triage`,{method:'POST',body:JSON.stringify({severity,status,resolution_note:note})}); await refresh('Incidencia actualizada.'); } catch(error){ toast(error.message,'danger'); } }

  return { pilotPage, enroll, withdraw, feedback, incident, manual, control, triage };
}
