'use strict';

import { api, app, esc, state, toast } from '../core.js';

export function createProfessionalExperience({ shell, pageHeader }) {
  const endpoint = '/api/m24/professional-network';
  const badge = (value) => {
    const text = String(value || 'pending');
    const cls = ['verified','accepted','available','clear','completed','on_time'].includes(text) ? 'green'
      : ['suspended','rejected','conflict','blocked','overdue'].includes(text) ? 'red' : 'yellow';
    return `<span class="badge ${cls}">${esc(text.replaceAll('_',' '))}</span>`;
  };
  const metric = (label, value, icon='§') => `<div class="kpi"><span class="kpi-label">${esc(label)}</span><div class="kpi-value"><strong>${esc(value)}</strong><span class="kpi-icon">${icon}</span></div></div>`;
  const assignmentCard = (row, specialistView=false) => `<article class="professional-assignment-card">
    <div><span class="eyebrow">${esc(row.product_code)} · ${esc(row.case_title || row.case_id)}</span><h3>${esc(row.specialist_name || 'Especialista')}</h3><p>${esc(row.offer_reason || '')}</p><div class="professional-meta">${badge(row.status)}${badge(row.conflict_status)}${badge(row.response_sla_status)}${row.review_due_at ? badge(row.review_sla_status) : ''}<span class="badge blue">Coincidencia ${esc(row.match_score)}/100</span></div></div>
    <div class="button-group">${specialistView && row.status === 'offered' ? `<button class="btn primary sm" data-action="professional-assignment-decision" data-assignment-id="${esc(row.id)}" data-decision="accept">Aceptar</button><button class="btn secondary sm" data-action="professional-assignment-decision" data-assignment-id="${esc(row.id)}" data-decision="reject">Rechazar</button>` : ''}${!specialistView && row.status === 'held' ? `<button class="btn primary sm" data-action="professional-conflict-resolve" data-assignment-id="${esc(row.id)}">Resolver conflicto</button>` : ''}${specialistView && row.status === 'accepted' ? `<button class="btn secondary sm" data-action="professional-assignment-complete" data-assignment-id="${esc(row.id)}">Cerrar asignación</button>` : ''}</div>
  </article>`;

  function specialistPage(data) {
    const profile = data.profile;
    const metrics = data.metrics || {};
    const assignments = data.assignments || [];
    let profilePanel = `<div class="empty-state"><h2>Sin invitación profesional</h2><p>La red profesional es cerrada y funciona únicamente por invitación administrativa.</p></div>`;
    if (profile) {
      const actions = profile.invitation_status === 'invited'
        ? `<button class="btn primary" data-action="professional-invitation-accept">Aceptar invitación</button>`
        : profile.verification_status === 'verified'
          ? `<button class="btn secondary" data-action="professional-availability" data-status="available">Disponible</button><button class="btn secondary" data-action="professional-availability" data-status="limited">Capacidad limitada</button><button class="btn secondary" data-action="professional-availability" data-status="unavailable">No disponible</button>`
          : '';
      profilePanel = `<div class="professional-profile-head"><div><span class="eyebrow">Perfil profesional cerrado</span><h2>${esc(profile.name || state.user.name)}</h2><p>${esc((profile.specialties || []).join(' · '))}</p></div><div class="professional-meta">${badge(profile.invitation_status)}${badge(profile.verification_status)}${badge(profile.availability_status)}</div></div><div class="professional-profile-grid"><span><small>Jurisdicción</small><b>${esc(profile.jurisdiction)}</b></span><span><small>Tarjeta</small><b>${esc(profile.bar_registration)}</b></span><span><small>Capacidad</small><b>${esc(metrics.active_assignments || 0)}/${esc(metrics.capacity || 0)}</b></span><span><small>Productos</small><b>${esc((profile.product_codes || []).length)}</b></span></div><div class="button-group mt-16">${actions}</div>`;
    }
    return `<div class="page">${pageHeader({eyebrow:'Red profesional cerrada',title:'Asignaciones y conflictos',description:'Red cerrada por invitación, capacidad verificable, declaración de conflictos y SLA auditables.'})}<section class="kpi-grid">${metric('Ofertas pendientes',metrics.offers_pending||0,'◌')}${metric('Asignaciones activas',metrics.active_assignments||0,'✓')}${metric('Capacidad',metrics.capacity||0,'▤')}${metric('SLA vencidos',(metrics.response_sla_overdue||0)+(metrics.review_sla_overdue||0),'!')}</section><section class="card mt-22">${profilePanel}</section><section class="card mt-22"><div class="card-header"><div><h2>Ofertas y asignaciones</h2><p>La aceptación no equivale a aprobación jurídica ni publicación del documento.</p></div></div><div class="professional-assignment-list">${assignments.length ? assignments.map(row=>assignmentCard(row,true)).join('') : '<div class="empty-state compact"><p>No tienes ofertas o asignaciones registradas.</p></div>'}</div></section><section class="card mt-22"><div class="legal-notice"><b>Privacidad de conflictos.</b> Los nombres contrastados no se conservan; únicamente se almacenan huellas HMAC-SHA256. La producción exige un secreto externo y validación de cumplimiento.</div></section></div>`;
  }

  function adminPage(data) {
    const metrics = data.metrics || {};
    const profiles = data.profiles || [];
    const specialists = data.eligible_specialists || [];
    const assignments = data.assignments || [];
    const cases = data.unassigned_cases || [];
    return `<div class="page">${pageHeader({eyebrow:'Gobierno profesional',title:'Red profesional cerrada',description:'Invitación, verificación, capacidad, conflictos de interés, asignación y SLA sin directorio público ni compensación real.'})}<section class="kpi-grid">${metric('Perfiles invitados',metrics.invited_profiles||0,'○')}${metric('Perfiles verificados',metrics.verified_profiles||0,'✓')}${metric('Ofertas pendientes',metrics.pending_offers||0,'◌')}${metric('SLA vencidos',metrics.overdue_slas||0,'!')}</section><section class="section-grid"><div class="card span-7"><div class="card-header"><div><h2>Especialistas</h2><p>Solo perfiles aceptados y verificados pueden recibir expedientes.</p></div></div><div class="professional-profile-list">${specialists.map(user=>{const profile=profiles.find(p=>p.user_id===user.id);return `<article><div><b>${esc(user.name)}</b><span>${esc(user.specialty||'Especialidad sin definir')}</span></div><div class="professional-meta">${profile?badge(profile.invitation_status):badge('not_invited')}${profile?badge(profile.verification_status):''}</div><div class="button-group">${!profile||profile.invitation_status==='declined'?`<button class="btn primary sm" data-action="professional-invite" data-specialist-id="${esc(user.id)}">Invitar</button>`:''}${profile?.invitation_status==='accepted'&&profile.verification_status==='pending'?`<button class="btn primary sm" data-action="professional-verify" data-specialist-id="${esc(user.id)}">Verificar</button>`:''}</div></article>`}).join('')}</div></div><div class="card span-5"><div class="card-header"><div><h2>Expedientes sin asignación</h2><p>La oferta es manual y exige coincidencia de producto y capacidad.</p></div></div><div class="professional-case-list">${cases.length?cases.map(row=>`<article><div><b>${esc(row.title)}</b><span>${esc(row.product_code)} · riesgo ${esc(row.risk)}</span></div><button class="btn secondary sm" data-action="professional-offer" data-case-id="${esc(row.id)}">Ofrecer</button></article>`).join(''):'<div class="empty-state compact"><p>No hay expedientes disponibles para oferta.</p></div>'}</div></div></section><section class="card mt-22"><div class="card-header"><div><h2>Asignaciones y conflictos</h2><p>Los casos retenidos por conflicto requieren decisión administrativa documentada.</p></div></div><div class="professional-assignment-list">${assignments.length?assignments.map(row=>assignmentCard(row,false)).join(''):'<div class="empty-state compact"><p>No hay asignaciones registradas.</p></div>'}</div></section><section class="card mt-22"><div class="card-header"><div><h2>Bloqueos para operación pública</h2></div></div><ul class="check-list muted-checks">${(data.production_blockers||[]).map(item=>`<li>${esc(item)}</li>`).join('')}</ul></section></div>`;
  }

  async function page() {
    const data = await api(endpoint);
    app.innerHTML = shell(state.user.role === 'specialist' ? specialistPage(data) : adminPage(data));
  }
  async function refresh(message) { if (message) toast(message); await page(); }
  async function invite(id) {
    const codes = prompt('Códigos de producto separados por coma:','CO-EM-003,CO-EM-004'); if (!codes) return;
    const last4 = prompt('Últimos cuatro dígitos de la tarjeta profesional:','0000'); if (!last4) return;
    const confirmation = prompt('Escribe INVITAR ESPECIALISTA AL PILOTO',''); if (!confirmation) return;
    try { await api(`${endpoint}/profiles/invite`,{method:'POST',body:JSON.stringify({specialist_id:id,product_codes:codes.split(',').map(x=>x.trim()),bar_registration_last4:last4,jurisdiction:'Colombia',max_active_cases:5,confirmation})}); await refresh('Invitación profesional registrada.'); } catch(error){ toast(error.message,'danger'); }
  }
  async function acceptInvitation() { const confirmation=prompt('Escribe ACEPTAR INVITACION PROFESIONAL',''); if(!confirmation)return; try{await api(`${endpoint}/profiles/accept`,{method:'POST',body:JSON.stringify({confirmation})});await refresh('Invitación aceptada; queda pendiente la verificación administrativa.');}catch(error){toast(error.message,'danger');} }
  async function verify(id) { const note=prompt('Evidencia o fundamento de verificación (mínimo 20 caracteres):','Cuenta y credenciales revisadas para el piloto interno.'); if(!note)return; const confirmation=prompt('Escribe VERIFICAR PERFIL PROFESIONAL',''); if(!confirmation)return; try{await api(`${endpoint}/profiles/verify`,{method:'POST',body:JSON.stringify({specialist_id:id,decision:'verified',note,confirmation})});await refresh('Perfil profesional verificado.');}catch(error){toast(error.message,'danger');} }
  async function availability(status) { try{await api(`${endpoint}/profiles/availability`,{method:'POST',body:JSON.stringify({availability_status:status})});await refresh('Disponibilidad actualizada.');}catch(error){toast(error.message,'danger');} }
  async function offer(caseId) { const data=await api(endpoint); const verified=(data.profiles||[]).filter(p=>p.verification_status==='verified'&&p.availability_status!=='unavailable'); if(!verified.length){toast('No hay especialistas verificados y disponibles.','danger');return;} const id=prompt(`ID del especialista:\n${verified.map(p=>`${p.user_id} · ${p.name}`).join('\n')}`,verified[0].user_id); if(!id)return; const reason=prompt('Justificación de la oferta (mínimo 20 caracteres):','Coincidencia de producto, especialidad y capacidad disponible.'); if(!reason)return; const confirmation=prompt('Escribe OFRECER EXPEDIENTE',''); if(!confirmation)return; try{await api(`${endpoint}/assignments/offer`,{method:'POST',body:JSON.stringify({case_id:caseId,specialist_id:id,reason,confirmation})});await refresh('Oferta profesional creada.');}catch(error){toast(error.message,'danger');} }
  async function decision(id,action) { if(action==='reject'){const note=prompt('Motivo del rechazo:','Capacidad o disponibilidad insuficiente.');if(!note)return;try{await api(`${endpoint}/assignments/${encodeURIComponent(id)}/decision`,{method:'POST',body:JSON.stringify({action:'reject',note})});await refresh('Oferta rechazada.');}catch(error){toast(error.message,'danger');}return;} const declaration=prompt('Conflicto: clear, conflict o needs_review','clear');if(!declaration)return;const parties=prompt('Partes o entidades contrastadas, separadas por coma:','Parte principal, Contraparte');if(!parties)return;const category=prompt('Categoría de relación:','none')||'none';const conflictNote=prompt('Nota general sin datos sensibles:','No se identificaron relaciones que afecten la independencia profesional.')||'';const confirmation=prompt('Escribe ACEPTAR EXPEDIENTE Y DECLARAR CONFLICTO','');if(!confirmation)return;try{await api(`${endpoint}/assignments/${encodeURIComponent(id)}/decision`,{method:'POST',body:JSON.stringify({action:'accept',conflict_declaration:declaration,parties:parties.split(',').map(x=>x.trim()),relationship_category:category,conflict_note:conflictNote,note:'Aceptación profesional del expediente.',confirmation})});await refresh('Decisión profesional registrada.');}catch(error){toast(error.message,'danger');} }
  async function resolve(id) { const decision=prompt('Resolución: clear o block','clear');if(!decision)return;const note=prompt('Fundamento de la resolución (mínimo 20 caracteres):','Se revisó la declaración y se documentó la decisión de gobierno.');if(!note)return;const confirmation=prompt('Escribe RESOLVER CONFLICTO DE INTERES','');if(!confirmation)return;try{await api(`${endpoint}/assignments/${encodeURIComponent(id)}/resolve-conflict`,{method:'POST',body:JSON.stringify({decision,note,confirmation})});await refresh('Conflicto resuelto.');}catch(error){toast(error.message,'danger');} }
  async function complete(id) { const note=prompt('Alcance del cierre profesional:','Revisión profesional concluida; la aprobación jurídica permanece en su flujo separado.');if(!note)return;const confirmation=prompt('Escribe CERRAR ASIGNACION PROFESIONAL','');if(!confirmation)return;try{await api(`${endpoint}/assignments/${encodeURIComponent(id)}/complete`,{method:'POST',body:JSON.stringify({note,confirmation})});await refresh('Asignación profesional cerrada sin alterar aprobaciones.');}catch(error){toast(error.message,'danger');} }
  return { page, invite, acceptInvitation, verify, availability, offer, decision, resolve, complete };
}
