from __future__ import annotations

PROJECT_NAME = "LegalAIZ.it"
MILESTONE = "M31.8"
VERSION = "5.0.7"
BUILD_ID = "M31-8-DEMO-EXPEDIENTES-REALES-2026-08-04"
RELEASE_ID = "M31-8-DEMO-EXPEDIENTES-REALES-5.0.7-2026-08-04"
RELEASE_NAME = "M31.8 — Demo integral por expediente y liberación documental"
RELEASE_DATE = "2026-08-04"
BASE_RELEASE = "M31.7 v5.0.6"
RELEASE_CHANNEL = "controlled_demo_case_workflows"
PRODUCTION_AUTHORIZED = False
PUBLIC_PRODUCTION_READY = False
POSTGRES_ADAPTER_IMPLEMENTED = True
POSTGRES_EXTERNAL_CERTIFIED = False
POSTGRES_BACKUP_RESTORE_CERTIFIED = False
POSTGRES_MIGRATION_CERTIFIED = False
CATALOG_RATIFICATION_MODEL = "historical_multi_stage_single_responsible"
DOCUMENT_RELEASE_APPROVAL_MODEL = "distinct_legal_and_qa_same_revision"
