# Historical release marker retained for immutable M31.1 evidence: M31-1-BASE-PREPRODUCCION-5.0.0-2026-08-03
# Historical M31.1 invariant: "production_authorized": False
from __future__ import annotations

from legalai_platform.release_metadata import (
    RELEASE_ID, RELEASE_NAME, RELEASE_CHANNEL, PRODUCTION_AUTHORIZED,
    DOCUMENT_RELEASE_APPROVAL_MODEL, CATALOG_RATIFICATION_MODEL,
)


def health_payload(*, version, build_id, settings, infrastructure_ready, approval_summary=None):
    return {
        "ok": True,
        "version": version,
        "build_id": build_id,
        "release_id": RELEASE_ID,
        "release_name": RELEASE_NAME,
        "production_authorized": PRODUCTION_AUTHORIZED,
        "professional_publication_authorized": bool((approval_summary or {}).get("professional_publication_authorized", True)),
        "experience": {
            "architecture": "role_based_case_centered",
            "release_channel": RELEASE_CHANNEL,
            "frontend_entry": "main.js",
            "frontend_modules": ["core.js", "ux_m21.js", "main.js"],
            "frontend_extension_modules": ["modules/ux_m24_7.js", "modules/pilot_m24_8.js", "modules/professional_m24_9.js", "modules/readiness_m25_0.js", "modules/pilot_center_m30_1.js", "modules/preproduction_m31_1.js"],
            "backend_route_modules": ["public_routes.py", "auth_routes.py", "system_routes.py", "product_quality_routes.py", "m24_candidate_routes.py", "m24_pilot_routes.py", "m24_full_routes.py", "m24_case_routes.py", "m24_client_routes.py", "m24_pilot_operations_routes.py", "m24_professional_routes.py", "m25_readiness_routes.py", "m30_pilot_center_routes.py", "m30_participant_routes.py", "m30_governance_routes.py", "m30_simulation_routes.py", "m30_live_evaluation_routes.py", "m31_preproduction_routes.py"],
            "design_system": "app.css",
            "legacy_workspace_available": False,
        },
        "profile": settings.profile,
        "infrastructure_ready": bool(infrastructure_ready),
        "runtime": {
            "profile": settings.profile,
            "infrastructure_ready": bool(infrastructure_ready),
            "api_contract": "2026-07-m21",
            "extension_contract": "2026-08-m24-candidate-1",
            "pilot_extension_contract": "2026-08-m24-pilot-2",
            "full_validation_extension_contract": "2026-08-m24-full-3",
            "case_journey_extension_contract": "2026-08-m24-case-4",
            "client_journey_extension_contract": "2026-08-m24-client-5",
            "guided_ux_extension_contract": "2026-08-m24-ux-7",
            "pilot_operations_extension_contract": "2026-08-m24-pilot-ops-8",
            "professional_network_extension_contract": "2026-08-m24-professional-9",
            "human_approval_extension_contract": "2026-08-m24-human-approval-10",
            "pilot_readiness_extension_contract": "2026-08-m25-readiness-0",
            "pilot_execution_center_contract": "2026-08-m30-pilot-center-1",
            "live_pilot_evaluation_contract": "2026-08-m30-live-evaluation-5",
            "preproduction_base_contract": "2026-08-m31-preproduction-1",
            "release_consolidation_contract": "2026-08-m31-consolidation-2",
            "release_reproducibility_contract": "2026-08-m31-reproducibility-3",
            "demo_documental_extension_contract": "2026-08-m31-demo-documental-7",
            "m24_candidate_integration": True,
            "m23_2_published": False,
            "m24_3_pilot_validation": True,
            "m24_3_distinct_dual_approval": True,
            "m24_4_full_validation": True,
            "m24_4_controlled_activation": True,
            "m24_5_case_journey": True,
            "m24_5_follow_up": True,
            "m24_6_client_intake": True,
            "m24_6_explainable_routing": True,
            "m24_6_offer_levels": True,
            "m24_6_checkout_to_case": True,
            "m24_7_short_question_blocks": True,
            "m24_7_review_before_analysis": True,
            "m24_7_responsive_guided_journey": True,
            "m24_7_fixture_visual_qa": True,
            "m24_8_controlled_pilot_operations": True,
            "m24_8_consent_and_privacy_minimization": True,
            "m24_8_incident_and_feedback_registry": True,
            "m24_8_release_gates_and_freeze": True,
            "m24_9_closed_professional_network": True,
            "m24_9_capacity_conflict_and_sla": True,
            "m24_9_no_public_directory_or_real_compensation": True,
            "m24_10_explicit_human_ratification": True,
            "m24_10_multi_stage_single_responsible_catalog_approval": True,
            "m24_10_public_production_still_blocked": True,
            "m25_0_pilot_readiness_audit": True,
            "m25_0_runtime_bindings_resolved": True,
            "m25_0_twenty_case_plan_supported": True,
            "m25_0_public_production_still_blocked": True,
            "m30_1_pilot_execution_center": True,
            "m30_1_structured_support_and_observations": True,
            "m30_1_public_production_still_blocked": True,
            "m30_5_live_pilot_evaluation": True,
            "m30_5_simulation_comparison": True,
            "m30_5_dual_go_no_go_approval": True,
            "m30_5_public_production_still_blocked": True,
            "m31_1_managed_preproduction_center": True,
            "m31_1_backup_drill_and_snapshots": True,
            "m31_1_public_production_still_blocked": True,
            "m31_2_release_identity_consolidated": True,
            "m31_2_distinct_document_approval_required": True,
        },
        "approval": approval_summary or {},
        "security": "sessions-rbac-csrf-required-mfa-scrypt-aes-gcm-encrypted-storage-encrypted-backups-rate-limits-origin-control-malware-gate-observability-privacy-governance-integrity",
        "security_controls": {
            "authentication": True, "rbac": True, "csrf": True, "mfa_available": True, "mfa_required_for_privileged_roles": True, "password_hashing": "scrypt",
            "encrypted_storage": True, "legacy_marker_deprecated": True,
        },
    }


def config_payload(*, version, build_id, settings, allowed_uploads, approval_summary=None):
    payload = {
        "version": version, "build_id": build_id, "release_id": RELEASE_ID,
        "release_name": RELEASE_NAME, "professional_publication_authorized": bool((approval_summary or {}).get("professional_publication_authorized", True)),
        "name": "LegalAIZ.it", "slogan": "Más que respuestas, soluciones.",
        "roles": ["client", "specialist", "admin"],
        "max_upload_mb": settings.max_upload_mb, "allowed_uploads": sorted(allowed_uploads),
        "authentication": True, "public_portal": True, "anonymous_diagnosis": True,
        "deployment": settings.public(), "mfa_available": True, "encrypted_storage": True,
        "server_drafts": True, "anonymous_encrypted_drafts": True, "payment_sandbox": True,
        "accessibility_target": "WCAG 2.2 AA (objetivo no certificado)",
        "experience_architecture": "role_based_case_centered", "release_channel": RELEASE_CHANNEL, "legacy_workspace_available": False,
        "api_contract": "2026-07-m21",
        "extension_contract": "2026-08-m24-candidate-1",
        "pilot_extension_contract": "2026-08-m24-pilot-2",
            "full_validation_extension_contract": "2026-08-m24-full-3",
            "case_journey_extension_contract": "2026-08-m24-case-4",
            "client_journey_extension_contract": "2026-08-m24-client-5",
            "guided_ux_extension_contract": "2026-08-m24-ux-7",
            "pilot_operations_extension_contract": "2026-08-m24-pilot-ops-8",
            "professional_network_extension_contract": "2026-08-m24-professional-9",
            "human_approval_extension_contract": "2026-08-m24-human-approval-10",
            "pilot_readiness_extension_contract": "2026-08-m25-readiness-0",
            "pilot_execution_center_contract": "2026-08-m30-pilot-center-1",
            "live_pilot_evaluation_contract": "2026-08-m30-live-evaluation-5",
            "preproduction_base_contract": "2026-08-m31-preproduction-1",
            "release_consolidation_contract": "2026-08-m31-consolidation-2",
            "release_reproducibility_contract": "2026-08-m31-reproducibility-3",
            "demo_documental_extension_contract": "2026-08-m31-demo-documental-7",
        "m24_candidate_integration": {"base_runtime": "M21.1", "candidate_library": "M23.2", "published": False, "active_generation_unchanged": True, "pilot_validation": "40/40", "pilot_products": 4, "full_validation": "110/110", "validated_products": 11, "activation_scope": "internal_professional_pilot_only"},
        "capabilities": {"cases": True, "documents": True, "legal_catalog": True, "review_workbench": True, "source_traceability": True, "document_factory": True, "audit": True, "deep_contractual_library_m4": True, "deep_legal_playbooks_m5": True, "release_candidate_m6": True, "preproduction_hardening_m7": True, "product_ux_m8": True, "technical_modularization_m9": True, "domain_routes_m10": True, "product_quality_registry_m10": True, "document_regeneration_m11": True, "lease_revalidation_m11": True, "product_quality_registry_m11": True, "service_contract_revalidation_m12": True, "product_quality_registry_m12": True, "confidentiality_ip_data_ai_revalidation_m13": True, "product_quality_registry_m13": True, "sast_verified_screening_m14": True, "product_quality_registry_m14": True, "traffic_notice_due_process_m15": True, "product_quality_registry_m15": True, "labor_settlement_revalidation_m16": True, "product_quality_registry_m16": True, "health_petition_revalidation_m17": True, "product_quality_registry_m17": True, "financial_habeas_data_revalidation_m18": True, "product_quality_registry_m18": True, "consumer_protection_revalidation_m19": True, "product_quality_registry_m19": True, "collection_payment_note_revalidation_m20": True, "product_quality_registry_m20": True, "ux_navigation_audit_m21": True, "role_based_navigation_m21": True, "guided_progress_m21": True, "m23_2_candidate_library_m24": True, "immutable_candidate_revision_integration_m24": True, "dual_approval_gate_m24": True, "pilot_scenario_execution_m24_3": True, "distinct_user_approvals_m24_3": True, "pilot_document_generation_m24_3": True, "full_scenario_execution_m24_4": True, "all_product_document_generation_m24_4": True, "controlled_internal_activation_m24_4": True, "end_to_end_case_journey_m24_5": True, "auditable_follow_up_m24_5": True, "explainable_client_intake_m24_6": True, "service_level_offer_m24_6": True, "sandbox_checkout_to_case_m24_6": True, "short_question_blocks_m24_7": True, "review_before_analysis_m24_7": True, "responsive_guided_journey_m24_7": True, "fixture_visual_qa_m24_7": True, "controlled_pilot_operations_m24_8": True, "consent_privacy_minimization_m24_8": True, "pilot_incident_feedback_m24_8": True, "release_gates_freeze_m24_8": True, "closed_professional_network_m24_9": True, "professional_capacity_conflict_sla_m24_9": True, "explicit_human_ratification_m24_10": True, "multi_stage_single_responsible_catalog_approval_m24_10": True, "pilot_readiness_audit_m25_0": True, "runtime_binding_resolution_m25_0": True, "controlled_twenty_case_plan_m25_0": True, "pilot_execution_center_m30_1": True, "structured_pilot_support_m30_1": True, "pilot_evidence_snapshot_m30_1": True, "participant_invitation_consent_m30_2": True, "participant_support_sla_m30_2": True, "participant_retention_schedule_m30_2": True, "pilot_communications_m30_3": True, "incident_governance_m30_3": True, "dual_approval_retention_m30_3": True, "cohort_closure_m30_3": True, "simulated_cohort_m30_4": True, "live_pilot_go_no_go_m30_5": True, "managed_preproduction_center_m31_1": True, "backup_restore_drill_m31_1": True, "release_identity_consolidation_m31_2": True, "distinct_document_approval_m31_2": True, "release_reproducibility_m31_3": True, "sanitized_distribution_m31_3": True, "automated_http_smoke_m31_3": True, "postgres_dual_persistence_m31_4": True, "postgres_certification_gate_m31_5": True, "external_certification_pipeline_m31_6": True, "complete_demo_document_generation_m31_7": True, "realistic_synthetic_portfolio_m31_7": True, "verified_docx_portfolio_m31_7": True},
        "production_authorized": PRODUCTION_AUTHORIZED,
        "approval_governance": {"catalog_ratification_model": CATALOG_RATIFICATION_MODEL, "document_release_model": DOCUMENT_RELEASE_APPROVAL_MODEL, "distinct_people_required": True},
        "compatibility": {"legacy_runtime_exposed": False, "legacy_frontend_removed": True, "historical_archive_packaged": False},
        "approval": approval_summary or {},
    }
    return payload
